### ISSUE TITLE
How to restore projects by using project.json instead of project.csproj? 

### ISSUE THREAD

**Issue by a1040147371** [OmniSharp/omnisharp-vscode#1185]
## Environment data
VS Code version:
1.9.0
C# Extension version:
1.6.2
## Steps to reproduce
I setup a project by the command `yo aspnet`, and then, want to run `dotnet restore`.

## Expected  behavior
it displays infomations as following:
`MSBUILD : error MSB1003: Specify a project or solution file. The current working
 directory does not contain a project or solution file.`

## Actual behavior
but there is a project.json file in the project root directory, there isn't a project.csproj file now.
Is it because the runtime found project.csproj file instead of project.json file?
How to set the runtime to find my project.json file?

**Comment by DustinCampbell** [comment]
Note that this is really a .NET Core SDK question rather than a question about C# in VS Code. However, the trick is to use a version of the .NET Core SDK that still supports project.json (preview2 builds of the .NET Core SDK are generally good). Then, add a global.json to the directory that looks like so:

```JSON
{
    "sdk": {
        "version": "1.0.0-preview2-1-003177"
    }
}
```

Or, you can add the "sdk" property to your existing global.json if it's already there. The version number should be for a .NET Core SDK version that you have installed. You can get the version I listed about at https://www.microsoft.com/net/download/core#/current if you don't have it already.

Once you have the "sdk" property pointing to a version of the .NET Core SDK supporting project.json that you have installed on your machine, all `dotnet` operations will use the specified version.

If you need further help, you might try asking on the https://github.com/OmniSharp/generator-aspnet repo, or https://github.com/dotnet/cli.

**Comment by DustinCampbell** [comment]
I'm going to go ahead and close these. Do let me know if the instructions above don't work for you.

**Comment by a1040147371** [comment]
thanks for your useful solution. And I'm sorry that I ask questions here, this is just because I don't know what the question reference from.

**Comment by DustinCampbell** [comment]
No worries about asking the question, just wanted to mention it in case you have other questions at the command-line. We might not be as equipped to answer those for you.
