### ISSUE TITLE
Debugger breaks code. Completely prevents user from debugging code. 

### ISSUE THREAD

**Issue by radding** [OmniSharp/omnisharp-vscode#1251]
I am using .NET Core and Visual Studio Code on a Linux mint sarah laptop. I am using 1.0.0-preview2-1-003177 for .NET and VSCode 1.8.1. I am running a ASP.NET Core application. If I call `dotnet run`, everything runs fine. But if I try to run the debugger, my application (Not visual studio Code) crashes. I get this error: Exception thrown: 'System.InvalidOperationException' in Microsoft.Extensions.Configuration.UserSecrets.dll on line 30 an startup.cs, which is computer generate. 

To reproduce:
Use linux mint. 
Run the debugger.
Get the error.

**Comment by DustinCampbell** [comment]
Could you provide the project that you're using to help us reproduce the issue? The steps as written aren't helpful without that.

**Comment by radding** [comment]
Unfortunately, I cannot provide the project.

**Comment by gregg-miskelly** [comment]
@radding there are two differences that we know of between `dotnet run` and hitting F5 on the project. You can try tweaking both of these to see if it resolves the issue. Otherwise we would need more information to try and help or direct you at the right repo.

Those two potential differences:
1. The default launch.json template enabled developer mode with `ASPNETCORE_ENVIRONMENT: "Development"` in launch.json. You can try removing that section.
2. The default launch.json templates will set the working directory (`cwd`) to the workspace root. If you don't have your project in the root of your workspace, this is a different than what you are using with `dotnet run`.

**Comment by DustinCampbell** [comment]
@radding: Did either of @gregg-miskelly's suggestions help?

**Comment by gregg-miskelly** [comment]
Closing for now. Feel free to reopen if this is still an issue.
