### ISSUE TITLE
Debugger: Remove breakpoint is invalid in the case of attach 

### ISSUE THREAD

**Issue by qian6** [OmniSharp/omnisharp-vscode#1266]
## Environment data
`dotnet --info` output:
VS Code version: 1.9.1
C# Extension version: [\\scratch2\scratch\janraj\vsdbg2\csharp-1.8.0-beta1.vsix ](\\scratch2\scratch\janraj\vsdbg2\csharp-1.8.0-beta1.vsix )
.NET Core SDK: 1.0.0-preview2-1-003177

## Steps to reproduce
1. Open hwapp folder in vscode .
[hwapp.zip](https://github.com/OmniSharp/omnisharp-vscode/files/803113/hwapp.zip)
2. Select “attach” configuration
3. Use command to run "dotnet exe" process.
4. Set a breakpoint at line of 11 in Program.cs and it hit breakpoint.
5. Remove breakpoint  and press continue.

## Expected  behavior
It should in running  mode.

## Actual behavior
It is in break mode.

**Comment by qian6** [comment]
This issue repro on windows.

**Comment by chuckries** [comment]
This issue stems from the fact that VS Code gives us a lower case drive letter in file paths on Windows. If the project is built in a working directory with an upper case file path, then file paths in the PDB will have upper case drive letters. We were doing a case sensitive comparison and believed we were working with two different files. This issue has been fixed in vsdbg and will be available soon.

**Comment by qian6** [comment]
Ok,Got it! Thanks!
