### ISSUE TITLE
High CPU and memory usage with csx script

### ISSUE THREAD

**Issue by veremenko-y** [OmniSharp/omnisharp-vscode#1306]
## Environment data
`dotnet --info` output:
```
$ dotnet --info
.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```
VS Code version: 1.10.2
C# Extension version: 1.7.0 (February 8, 2017)

## Steps to reproduce

[reproduce.zip](https://github.com/OmniSharp/omnisharp-vscode/files/832079/reproduce.zip)
1. Restore scriptcs packages
2. Start using Intelisence, memory usage will spike almost immediately

## Expected  behavior

Let me work and not behave like a Chrome

## Actual behavior

O_o
Use all available memory while typing 10-15 lines.
![image](https://cloud.githubusercontent.com/assets/4127660/23767090/7d09a4c8-04c4-11e7-8934-16274c86272a.png)

**Comment by filipw** [comment]
thanks for the report. 

we have to call @DustinCampbell and @tmat for help here. All that memory is seen in the profiler as "unmanaged code", and from what I can see, there is no memory leak on the managed side. 

Would this be due to Roslyn internally compiling the script submissions over and over? We never compile the script in OmniSharp ourselves, we just create a `ProjectInfo`, add to the workspace and pass in `CompilationOptions` that are relevant for scripting.

**Comment by filipw** [comment]
When the default `ScriptMetadataResolver` here https://github.com/OmniSharp/omnisharp-roslyn/blob/dev/src/OmniSharp.Script/ScriptProjectSystem.cs#L48 is removed, the problem goes away, but of course `#r` doesn't work anymore.

This default implementation is suitable for runtime usage, should we be using a different implementation for providing language services?

**Comment by veremenko-y** [comment]
I can confirm if I remove all `#r` from the code, it consumes around 70 MBytes of the memory. Is there anything else I can help with in this case?

**Comment by veremenko-y** [comment]
@filipw I replaced the bin folder in vscode plugin with newly build OmniSharp from dev branch. Nothing suspicious in the log, but it fails to even detect System.Object. Did I do something wrong?
![image](https://cloud.githubusercontent.com/assets/4127660/23806500/2376a74c-057f-11e7-88ae-ee24c6dbe1ff.png)

**Comment by filipw** [comment]
@veremenko-y when the VS Code C# Extension is distributed, it doesn't use the netcoreapp build of Omnisharp but rather the net46 one (via embedded mono). 
You should use that version for consistency rather than - from what is seems to me on the screenshot - the .NET Core one.

Also note that you don't need to replace anything in the extension folder, you can just point to the omnisharp build location from the user settings, i.e.:

```
    "omnisharp.path": "C:\\code\\omnisharp-roslyn\\src\\OmniSharp\\bin\\Debug\\net46\\OmniSharp.exe",
```

There are known issues with scripting support via .NET Core version of the server. Due to the nature of Roslyn scripting, it needs to implicitly reference `object` assembly (known at runtime, not compile time). When server is compiled against .NET Core, it references `System.Object` through `System.Runtime` assembly, which in turn forwards the type to `System.Private.CoreLib`, while in your case the script needs classic `mscorlib`. OTOH, in such cases it supports .NET Core (not desktop CLR) C# scripts well.

**Comment by veremenko-y** [comment]
Thank you again, @filipw . You guys are awesome with such quick response.
