### ISSUE TITLE
Create setting to manually configure system linux distro

### ISSUE THREAD

**Issue by shealey** [OmniSharp/omnisharp-vscode#1361]
I'm building and running .Net core apps on GalliumOS - a lightweight Linux distro based on Ubuntu 16.10 (http://www.galliumos.org).

When I try to launch the debugger, I get the error message "The current Linux distribution 'galliumos' version '2.1' is not currently supported by the .NET Core debugger. Debugging will not be available."

Could we add a VsCode setting for Omnisharp so that users can specify what debugger version to use, in my instance ubuntu 16.10 so that it will work on more Linux distros?

Thanks

**Comment by gregg-miskelly** [comment]
@shealey that sounds like a reasonable idea. Though if you wouldn't mind, can you try editing your platform.js file to see if things work if you change the following line from '2.0' to '2.1'?

https://github.com/OmniSharp/omnisharp-vscode/blob/master/src/platform.ts#L331

**Comment by shealey** [comment]
Hi Gregg,

Changing the version from 2.0 to 2.1 did the trick and I'm now able to debug as a temporary workaround.

Thanks

**Comment by WardenGnaw** [comment]
@gregg-miskelly Should we have a setting to specify the version of ID_LIKE? E.g. csharp.idLikeVersion: { "ubuntu": "14.04" }? Since several OS's, like Zorin, utilize VERSION to be associated with ID, but KDE Neon uses a version of Ubuntu.

Using this page as reference: https://github.com/zyga/os-release-zoo
