### ISSUE TITLE
Initializing project system triggers incorrect restore prompt and reprocesses projects multiple times

### ISSUE THREAD

**Issue by natemcmaster** [OmniSharp/omnisharp-vscode#141]
# Repro step

Clone entity framework to Mac.
From command line: `dotnet restore` (should succeed)
Open VS Code.
Select the whole "solution" in "Omnisharp: Select Project".
# Expected behavior

Initialize project state and intellisense. No restore necessary.
# Actual behavior

VS Code produces dozens of errors _"There are unresolved dependencies from '(project)'. Please execute the restore command to continue."_ This is produce multiple times per project.

Furthermore, the Omnisharp output shows it is continually processing the same projects over and over. Appears to have processed each project state about 40 times.

Full log: 
[omnisharp-log.txt](https://github.com/OmniSharp/omnisharp-vscode/files/204848/omnisharp-log.txt)

After about ~4 minutes, project initialization appears done and omnisharp operates as expected.
# My setup

VS Code 0.10.11
Using C# 0.3.7
Using omnisharp-roslyn build locally from https://github.com/OmniSharp/omnisharp-roslyn/commit/aab690c (result of mergeing https://github.com/OmniSharp/omnisharp-roslyn/pull/501)

**Comment by gregg-miskelly** [comment]
The version of the C# extension that you have isn't really meant to work with .NET CLI. You can build the dev branch if you want something that should work.

**Comment by troydai** [comment]
@gregg-miskelly I believe @natemcmaster is indeed use the OmniSharp-Roslyn build from dev branch. 

The problem here is the effect of combination of omnisharp-roslyn's relentless restore effort and VS Code's notification mode. Here's what happened. When O# loads the projects it looks at each projects' dependencies. If there are any unresolved dependencies, it triggers a `dotnet restore`. Once restore finishes it update the lock file which cause the O# to reload the project. If there are still unresolved dependencies, it will send message to VS Code which cause the notification.

In the case when there are a lot of unresolved projects, for example negative test case samples, there will be a lot of warning messages.

This is indeed something we can improve.

**Comment by DustinCampbell** [comment]
Reclassifying this issue. It isn't really a bug since it's working as it was implemented ages ago. However, the experience is terrible. :smile:

**Comment by akshita31** [comment]
VS Code version: 1.22.2
C# Extension Version: 1.14
O# version: 1.29.1

I have a solution with 10 projects. If I execute the `dotnet restore` before opening the solution in vscode, no 'Restore' notifications pop up. And if I dont do a dotnet restore before hand, then for each project the warning message appears only once. 

@natemcmaster Can you check if the issue reproduces for the updated version of the extension as well ?

**Comment by natemcmaster** [comment]
No repro anymore. A few things have changed in the project system since the days of project.json. I'm sure somewhere in the last 2 years someone already fixed this. Thanks for the follow up though.
