### ISSUE TITLE
Snippets: autocomplete issue for "FOR" / "FOREACH" / maybe others snippets with iterators

### ISSUE THREAD

**Issue by Leopotam** [OmniSharp/omnisharp-vscode#1492]
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.1
```

VS Code version:
1.13.0-insider (1.13.0-insider) 3bb9b5314ef50bd8225aba0565cadc6ca19bc821 2017-05-18T06:18:32.269Z

C# Extension version:
1.10.0-beta3 dc1908d0e984a52536289f34fe4be5f80eb94f10
## Steps to reproduce
1. Enter "for" and press tab twice.
## Expected  behavior
```
for (int i = 0; i < max; i++)
{
    
}
```
## Actual behavior
```
for (int  = 0;  < ; ++)
{
                    
}
```

**Comment by DustinCampbell** [comment]
I think this is probably a VS Code issue. AFAICT, it only repros when the `for` snippet is expanded while another snippet is already active. @jrieken: Does this look familiar?

Repro steps:

1. Create new C# file.
2. Type `class` and press <kbd>TAB</kbd> twice to expand the 'class' snippet and position the caret in the middle of the class. Be sure _not_ to press <kbd>ENTER</kbd> to keep the 'class' snippet active.
3. Type `svm` and press <kbd>TAB</kbd> to create a new static Main method with the caret positioned inside.
4. Type `for` and press <kbd>TAB</kbd> twice.

**Comment by cateyes99** [comment]
My one gives me the proper code, using `C# Extension version 1.8.1`:
```
class Name
{
    static void Main(string[] args)
    {
        for (int i = 0; i < length; i++)
        {
            
        }
    }
}
```
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.1
```
`VS Code version`: 1.12.1
`C# Extension version`: 1.8.1

**Comment by DustinCampbell** [comment]
I'm not sure what you mean @cateyes99. I just downloaded and tried 1.8.1 of C# for VS Code and can repro the same issue using the steps I provided above.

![image](https://cloud.githubusercontent.com/assets/116161/26229513/10a70874-3bf7-11e7-98ce-e4622ad2ade0.png)

Be sure not to press <kbd>ENTER</kbd> after expanding the `class` template. Instead, leave it active before expanding the `for` template.

**Comment by jrieken** [comment]
Yeah, we did push a change to our snippet logic that we announced last November. I am sorry, but somehow this extension isn't on our list: https://github.com/Microsoft/vscode/issues/15573

In short, we had an internal snippet syntax that could accidentally be used via the API and that also leaked into parsing of Textmate-snippets. Since November we have a documented and well-defined snippet syntax and we were supporting both (internal & official syntax) for a while. The new syntax is documented here: https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax

Also, since we might have forgotten some (static) snippets I check what I can do here... We can turn on support for the old syntax again, but support for it won't be that nice anymore.

**Comment by DustinCampbell** [comment]
@jrieken: So, if I understand you correctly, the fix for us is to rewrite our snippets?

**Comment by jrieken** [comment]
Yes, that would be very nice. The problem is that your snippets contain something like `${foo}` which in textmate terms is a variable. The internal syntax used to look yet different and there used to be some layer massaging the string from one format into another one (to make it then parsed as placeholder). That logic had many flaws and should have never accept `${foo}`, the correct syntax for a placeholder/tabstop is `${1:foo}`.  

I can look into making a PR if you guys did plan for this change yet.
