### ISSUE TITLE
Unable to attach to CoreCLR. Unknown Error: 0x8007054f Linux OpenSUSE 

### ISSUE THREAD

**Issue by roblourens** [OmniSharp/omnisharp-vscode#1513]
_From @jesa1 on May 24, 2017 5:42_

- VSCode Version: 1.12.
- OS Version: OpenSUSE 42.2

Steps to Reproduce:

1. Updated Visual Studio Code to  1.12 using  OpenSUSE  instructions on https://code.visualstudio.com/docs/setup/linux#_rhel-fedora-and-centos-based-distributions

2. Opened  a folder  created  from  dotnet new mvc

3. selected the Menu Option Start  with Debugging

dotnet --info output
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     opensuse
 OS Version:  42.2
 OS Platform: Linux
 RID:         opensuse.42.1-x64
 Base Path:   /opt/dotnet/sdk/1.0.4

in previous  version and  current  version  using the  menu  option  start without debugging  the  website  does  start  in the  browser. I get the  following  output  

Executing action method webtest.Controllers.HomeController.Index (webtest) with arguments ((null)) - ModelState is Valid
info: Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewResultExecutor[1]
      Executing ViewResult, running view at path /Views/Home/Index.cshtml.
info: Microsoft.Extensions.DependencyInjection.DataProtectionServices[0]
      User profile is available. Using '/home/jesa/.aspnet/DataProtection-Keys' as key repository; keys will not be encrypted at rest.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action webtest.Controllers.HomeController.Index (webtest) in 2748.0252ms
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/js/site.js?v=EWaMeWsJBYWmL2g_KkgXZQ5nPe-a3Ichp0LEgzXczKo  
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/js/site.js'. Physical path: '/home/jesa/projects/webtest/wwwroot/js/site.js'
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 3125.0155ms 200 text/html; charset=utf-8
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 112.4478ms 200 application/javascript

 but  when attempting to use  the  Start Debugging option  I always get the  error

You may only use the Microsoft .NET Core Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.

Unable to attach to CoreCLR. Unknown Error: 0x8007054f

_Copied from original issue: Microsoft/vscode#27177_

**Comment by gregg-miskelly** [comment]
I setup an OpenSUSE 42.2 box but debugging worked for me.

@jesa1: What version of CoreCLR is your app running under? Assuming you are using the shared framework, you can check what version you have installed with `ls /opt/dotnet/shared/Microsoft.NETCore.App/`.

**Comment by jesa1** [comment]
the  output  from ls /opt/dotnet/shared/Microsoft.NETCore.App/   is
1.1.2

**Comment by gregg-miskelly** [comment]
@jesa1 Can you try this:

1. Open a shell, and start your .NET Core web app (ex: `cd myProjDir` and `dotnet run`)
2. Open another shell
3. `pgrep dotnet -a` and look for the 'dotnet exec \<path-to-your-app>' process.
4. `grep libcoreclr.so /proc/\<process-id-from-step-3\>/maps`
5. Paste in the output

Example:
```
vsdbg@greggm-70524b:~> pgrep dotnet -a
2383 dotnet run
2431 dotnet exec /home/vsdbg/cliweb/bin/Debug/netcoreapp1.1/cliweb.dll
vsdbg@greggm-70524b:~> grep libcoreclr.so /proc/2431/maps
7fdd750b2000-7fdd75335000 r-xp 00000000 08:01 1443927                    /opt/dotnet/shared/Microsoft.NETCore.App/1.1.2/libcoreclr.so
7fdd75335000-7fdd75336000 rwxp 00283000 08:01 1443927                    /opt/dotnet/shared/Microsoft.NETCore.App/1.1.2/libcoreclr.so
7fdd75336000-7fdd75617000 r-xp 00284000 08:01 1443927                    /opt/dotnet/shared/Microsoft.NETCore.App/1.1.2/libcoreclr.so
7fdd75617000-7fdd75618000 rwxp 00565000 08:01 1443927                    /opt/dotnet/shared/Microsoft.NETCore.App/1.1.2/libcoreclr.so
7fdd75618000-7fdd757e6000 r-xp 00566000 08:01 1443927                    /opt/dotnet/shared/Microsoft.NETCore.App/1.1.2/libcoreclr.so
7fdd757e6000-7fdd759e5000 ---p 00734000 08:01 1443927                    /opt/dotnet/shared/Microsoft.NETCore.App/1.1.2/libcoreclr.so
7fdd759e5000-7fdd75a40000 r--p 00733000 08:01 1443927                    /opt/dotnet/shared/Microsoft.NETCore.App/1.1.2/libcoreclr.so
7fdd75a40000-7fdd75a49000 rw-p 0078e000 08:01 1443927                    /opt/dotnet/shared/Microsoft.NETCore.App/1.1.2/libcoreclr.so
```

**Comment by jesa1** [comment]
<pre><code>jesa@imhotep5:~> pgrep dotnet -a
7058 dotnet run
7093 dotnet exec /home/jesa/projects/webtest/bin/Debug/netcoreapp1.1/webtest.dll
jesa@imhotep5:~> grep libcoreclr.so /proc/7093/maps
7f598a7bb000-7f598aa3e000 r-xp 00000000 00:3a 13701                      /opt/dotnet/shared/Microsoft.NETCore.App/1.1.2/libcoreclr.so
7f598aa3e000-7f598aa3f000 rwxp 00283000 00:3a 13701                      /opt/dotnet/shared/Microsoft.NETCore.App/1.1.2/libcoreclr.so
7f598aa3f000-7f598ad20000 r-xp 00284000 00:3a 13701                      /opt/dotnet/shared/Microsoft.NETCore.App/1.1.2/libcoreclr.so
7f598ad20000-7f598ad21000 rwxp 00565000 00:3a 13701                      /opt/dotnet/shared/Microsoft.NETCore.App/1.1.2/libcoreclr.so
7f598ad21000-7f598aeef000 r-xp 00566000 00:3a 13701                      /opt/dotnet/shared/Microsoft.NETCore.App/1.1.2/libcoreclr.so
7f598aeef000-7f598b0ee000 ---p 00734000 00:3a 13701                      /opt/dotnet/shared/Microsoft.NETCore.App/1.1.2/libcoreclr.so
7f598b0ee000-7f598b149000 r--p 00733000 00:3a 13701                      /opt/dotnet/shared/Microsoft.NETCore.App/1.1.2/libcoreclr.so
7f598b149000-7f598b152000 rw-p 0078e000 00:3a 13701                      /opt/dotnet/shared/Microsoft.NETCore.App/1.1.2/libcoreclr.so</code></pre>

**Comment by gregg-miskelly** [comment]
Well, that certainly looks good. I will try to get you more instructions next week to try and understand what is going wrong.

**Comment by jesa1** [comment]
Where  do I go from here?   I have  done a  pull of  the   code to  attempt  to debug   but  there  were  other  issues  so far  that I need to  patch up the  code  for,  like  getting past  Error processing 'configurationDone' request. Unknown Error: 0x897200 

Once  I get  pass  the new errors  encountered  in building  from source  where  should  I be  looking  in the  code  to  find the  source  of  ERROR_INTERNAL_ERROR coming from CoreCLR?

**Comment by gregg-miskelly** [comment]
It sounds like you are trying to build VS Code, is that right? The debugger actually doesn't support the OSS version of VS Code and that is what that weird internal error means.

The project that would be useful to build in order to get a debug copy is coreclr. I tried to do this when your bug came in but I found I didn't know enough about OpenSUSE to get my box configured to build it. But if you can succeed, go for it! I would recommend checking out a branch at a tag. You likely want tag 'v1.1.2'. 

If you don't have the time, or don't succeed, we are in the middle of switching to .NET Core 2.0 (see https://github.com/OmniSharp/omnisharp-vscode/pull/1576). I doubt this will fix the problem, but it will make it easier for me to give you a private.

At any rate, the first dll to try and patch is libdbgshim.so. You want to copy the one you build from the CoreCLR repo into the directory where the debugger is installed (ex: /home/\<alias\>/.vscode/extensions/ ms-vscode.csharp-1.10.0/.debugger). You can then either try and native debug libdbgshim.so or get it to output traces.

Either way the easiest way to do this is to run `./vsdbg-ui --server --consoleLogging`. Then you want to modify your launch.json file in VS Code to connect to this running instance of the debugger by adding `"debugServer":4711` into your active configuration.

If you want to try debugging through in libdbgshim, is [RegisterForRuntimeStartup](https://github.com/dotnet/coreclr/blob/2efbb9282c059eb9742ba5a59b8a1d52ac4dfa4c/src/dlls/dbgshim/dbgshim.cpp#L625).

If you want to try using their tracing, I believe the right way to do the tracing is to set the set of channels to trace with `export PAL_DBG_CHANNELS="+PROCESS.TRACE"` and set the tracing file with `export PAL_API_TRACING=dbgshimlog.txt`

**Comment by gregg-miskelly** [comment]
One more thing I should add: I will be on vacation next week, so you probably will not hear back from me right away if you have questions.

**Comment by jesa1** [comment]
I now  have  debugging  working
I upgraded to  .Net Core 2.0 Preview 2
I upgraded  Visual Studio Code  to   1.13.1

Thanks  for  all of  your help  and  hard work.

**Comment by gregg-miskelly** [comment]
Great!
