### ISSUE TITLE
Use dotnet tools from within a docker container to provide language services

### ISSUE THREAD

**Issue by ggobbe** [OmniSharp/omnisharp-vscode#1533]
Hi,

I do not know how feasible it would be but it would be great to be able to use the dotnet installation from a docker container to provide the dotnet tools required by OmniSharp in Visual Studio Code.

The main goals would be:

- No need to install the dotnet sdk on the host machine, a machine running docker will suffice. This will also keep the host OS clean from having to install successive versions of .NET.
- OSes where Visual Studio Code run but dotnet is not supported can use a docker container to get their development environment set up (e.g. Arch and other Linux distributions not officialy supported by .NET Core)

As said, I do not know if it is possible to expose the dotnet tools from a docker container as a service available outside of the docker container (through a volume?).

Thanks

**Comment by DustinCampbell** [comment]
I don't think we'd support this out of the box, but I suspect you *could* achieve it by mapping `dotnet` to an installation of .NET Core SDK in a docker container through a volume. In VS Code and OmniSharp, we only interact with the .NET Core SDK by shelling out to `dotnet`. OmniSharp *might* need a bit of extra because it tries to locate the .NET Core SDK by calling `dotnet --info` and then using the `Base Path` in the info text. If that path is local to the container, it wouldn't work for OmniSharp.

**Comment by richlander** [comment]
/cc @kendrahavens @glennc

We talked about this scenario today in our Docker sync. We would like to explore Docker integration more with VS Code. This isn't the very first thing on our list, but I could see it coming out of more general investment.

**Comment by DustinCampbell** [comment]
It may also be possible to do this by creating a docker image that contains not just the .NET Core SDK, but also OmniSharp itself. I imagine that one could create a shell script that calls `docker run` with the right arguments to launch OmniSharp and set `omnisharp.path` within VS Code to that script. If it works like I expect, C# for VS Code would communicate properly with the OmniSharp process in the docker container over stdin/stdout.

**Comment by richlander** [comment]
That makes sense. That would be straightforward to do. It would be straightforward to create an image that does this. I'd be happy work on a demo with you. There are few bits of info I'd need to get the image ready.

**Comment by gregg-miskelly** [comment]
Two notes in case they are not obvious:

1. .NET Core 2.0 will support a much larger set of Linux Distros. So it should no longer be necessary to run tools in containers due to a lack of support on the OS running VS Code. 
2. To my knowledge we still do not have a sample project that shows how to tie together Docker + .NET Core + VS Code so that one can easily build one's app into a container, launch an app into Docker with F5, and attach to a running Docker project. While running all the tools in a container sounds cool. Personally I think this sounds more like 'running' and I think we are still flat or our faces being unable to move :).

**Comment by DustinCampbell** [comment]
>While running all the tools in a container sounds cool. Personally I think this sounds more like 'running' and I think we are still flat or our faces being unable to move :).

I agree completely. :smile: For me, this is more of a thought exercise.

**Comment by sleemer** [comment]
@ggobbe 
I managed to find a kind of a solution for your case ( you can find it in my repo on https://github.com/sleemer/docker.dotnet.debug)  ... The only downside of such approach, that you can't start debugging in container - you can only attach to existing one. One of the possible workarounds could be delaying execution of the debugged application in container by modifying ENTRYPOINT in Dockerfile.debug and adding some sleep operator. But, personally, I don't like such hacks... but I can't think of any other solutions for now. Hope it will help you.

**Comment by ggobbe** [comment]
@sleemer thanks, does it support intellisense (autocompletion) as well?

**Comment by sleemer** [comment]
@ggobbe Actually not, it just gives you the ability to run and debug your app in the same environment as it will be on prod. But I see your point, you want to be able to develop in container as well, and not only be able to debug it inside the container... so, I don't think that we are there yet with current tooling...  but that would be nice option to have in the future)

**Comment by jlhogan** [comment]
hey @richlander / @gregg-miskelly / @DustinCampbell  any movement on this? Attempting to build a docker-compose project for dotnet development for my team which works across multiple OSs and setups, and includes a SQL Server backend. Would love to be able to provide a setup that enables omnisharp syntax checking etc. for those developing with VSCode. Thanks!

**Comment by jballe** [comment]
Maybe VS Code Remote for Container handles this better (even tough it is only Linux so far, but I guess they are working with everyone to make a Windows version possible)
