### ISSUE TITLE
Bad install/update experience because the server is too slow from Chengdu.CHINA

### ISSUE THREAD

**Issue by kissstudio** [OmniSharp/omnisharp-vscode#1542]
Can you please add some  mirror server at Asia area because the extension install/update experience is so bad, it's too slow to get the omnisharp extension from your server from here.

Updating C# dependencies...
Platform: win32, x86_64

Downloading package 'OmniSharp (.NET 4.6 / x64)' (15684 KB) .................... Done!
Downloading package '.NET Core Debugger (Windows / x64)' (43510 KB) .

about half hour will be spend at every time update...

by the way, the bandwidth here is 100M FDDI

**Comment by gregg-miskelly** [comment]
Was it the debugger part that was slow, or OmniSharp? The debugger is actually already behind a CDN. So, unless something was wrong with it at the time you requested, it should have pulled it from somewhere in Asia.

**Comment by King66** [comment]
The debugger is more slower in China..
You can use azure china like vscode.. https://code.visualstudio.com/updates/v1_12#_china-downloads

**Comment by 50774283** [comment]
I have same issue. I have take 1 hours for download OmniSharp still failed.

**Comment by kissstudio** [comment]
@gregg-miskelly 
i tried again just now, both of them is slow as before.
OmniSharp tasks about 9 min and the debugger takes 4 min to get up about 20%.

@King66 
and i tried the vscode download, the speed is so quick now.  ^^

**Comment by gregg-miskelly** [comment]
We are hoping to switch to a new system for 1.12 which I hope will making things better.

**Comment by renkun-ken** [comment]
Same issue here in Shanghai. Extremely slow at "Downloading package xxx", always takes hours.

**Comment by gregg-miskelly** [comment]
We completed the work to switch to a new CDN for 1.12. If you are the unlucky person who needs to warm up the CDN - this might not be much better. But for everyone else, this should be a big improvement, at least in China.

If anyone wants to try it out, here are [instructions](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases). Keep in mind that since it is a beta, the CDN may not be warmed up in your region, so you may need to download twice to see the improvement.
