### ISSUE TITLE
Exceptions not working properly

### ISSUE THREAD

**Issue by ramya-rao-a** [OmniSharp/omnisharp-vscode#1564]
_From @RenaudThoraval on June 12, 2017 14:52_

- VSCode Version: 1.13.0
- OS Version: macOS Sierra 10.12.5 / Windows 10 Enterprise 1607

**Steps to Reproduce:**

1. Open a .NET Core project (reproduced with .NET Core 1.1)
2. Add a line which causes an exception (division by 0 for example or even `Debug.Assert(false)`)
3. Run the code in debug

**Expected behaviour:**

Visual Studio Code breaks on the line and display exception, as in previous version.

<img width="1409" alt="exception_break_ok" src="https://user-images.githubusercontent.com/16089684/27039733-1914d67a-4f8f-11e7-94c7-73c8ed5e7669.png">

**Actual behaviour:**

Visual Studio Code breaks but doesn't show the line and the exception. The debug panel remains empty for every thread.

<img width="1420" alt="exception_break_ko" src="https://user-images.githubusercontent.com/16089684/27039740-218155cc-4f8f-11e7-8a4a-a0b85c5b7c63.png">

I reproduced this bug also on latest Insider version (1.14.0). I also reproduced it on a fresh install with only Omnisharp extension (ms-vscode.csharp) in 1.10.0, 1.11.0-beta and 1.9.0 to be sure that it's a Visual Studio Code issue.

_Copied from original issue: Microsoft/vscode#28536_

**Comment by ramya-rao-a** [comment]
@RenaudThoraval C# debugging is implemented by the C# extension. The extension owners will be able to specify if the issue you are seeing is due to the extension or VS Code.

**Comment by gregg-miskelly** [comment]
@renaudthoraval it looks like the problem is that the call stack doesn't show your code on it. If you disable 'justMyCode' in your launch.json, what call stack do you see?

**Comment by RenaudThoraval** [comment]
@gregg-miskelly I already tried to disable JusMyCode but it doesn't solve the problem. I had to install previous version of VS Code (1.12.2) in order to have proper exception behaviour. Debug assertions don't work properly too. A `Debug.Asset(false)` doesn't break as expected, like exception. VS Code doesn't switch the the line with the assertion and nothing appears in the debug panel.
I tried with your extension in previous stable version (1.9.0) and also in future version in beta (1.11) and it's still the same problem.
I think it's related to VS Code 1.13 update because there is no problem with a clean install of VS Code 1.12.2. As soon as I update editor in current version or in insider, exceptions and assertions stop working.
I first posted my ticket in VS Code GitHub repo but I was redirected here. I hope you can help me :)

**Comment by ramya-rao-a** [comment]
@gregg-miskelly @RenaudThoraval Closing this issue in favor of the original one. It wasnt clear to me before that this was a regression.
