### ISSUE TITLE
VSCode fails to automatically install .Net Core Debugger upon opening a C# folder after upgrading CLI from release to latest beta

### ISSUE THREAD

**Issue by mattscheffer** [OmniSharp/omnisharp-vscode#161]
VSCode Version: 0.10.11
OS Version: OSX, Win10

This assumes you already have openssl installed.

1. Install VSCode
2. Install Release version of the Dotnet CLI from https://dotnet.github.io/getting-started/
3. Install latest C# extension
4. Install latest beta version of the DotNet Cli from https://github.com/dotnet/cli
5. Open VSCode. Open folder with a C# project inside.

Expected:
.Net Core debugger should install automatically

Actual:
Pop up appears saying the there was an error when installing .NET Core Debugger. Has a button for view log, but nothing happens if you click it.

dotnet --info:
.NET Command Line Tools (1.0.0-rc2-002306)

Product Information:
Version:              1.0.0-rc2-002306
Commit Sha:     0747d31f86

Runtime Environment:
OS Name:           Mac OS X
OS Version:       10.11
OS Platform:     Darwin
RID:                   osx.10.11-x64

**Comment by gregg-miskelly** [comment]
#159 tracks improving the logging for this scenario.

The issue is that when VS Code (or other processes) run 'dotnet' they are still getting the old version of it --
Starting 'dotnet --info'
Error: Unknown option: --info
.NET Command Line Tools (1.0.0-beta-001598)
Usage: dotnet mmon-options] mmand] guments]
 
Arguments:
  mmand]     The command to execute
  guments]   Arguments to pass to the command
 
Common Options (passed before the command):
  -v|--verbose  Enable verbose output
  --version     Display .NET CLI Version Info
 
Common Commands:
  new           Initialize a basic .NET project
  restore       Restore dependencies specified in the .NET project
  build         Builds a .NET project
  publish       Publishes a .NET project for deployment (including the runtime)
  run           Compiles and immediately executes a .NET project
  repl          Launch an interactive session (read, eval, print, loop)
  pack          Creates a NuGet package
Error: 'dotnet --info' failed with error 1
Ensure that .NET Core CLI Tools version >= 1.0.0-beta-002173 is installed. Run 'dotnet --version' to see what version is installed.

**Comment by gregg-miskelly** [comment]
I will update our documentation to have a 'troubleshooting section' where I mention this.

**Comment by gregg-miskelly** [comment]
Documentation updated.
