### ISSUE TITLE
.NetCore Intellisense not refreshing when packages added

### ISSUE THREAD

**Issue by jsheely** [OmniSharp/omnisharp-vscode#1661]
- VSCode Version: 1.14.2
- OS Version: Windows 10 Pro 64-bit

Steps to Reproduce:
1. Open VSCode
2. Use Terminal to dotnet new webapi
3. dotnet add package serilog.sinks.elasticsearch
4. Yes to restore packages
5. Try to configure ```new LoggerConfiguration().writeTo.Elasticsearch``` (Elasticsearch is not available)
6. Close VSCode & Reopen
7. Elasticsearch will now be available to intellisense

Attached is a video of the process.
https://dl.dropboxusercontent.com/u/10620012/2017-07-23_18-42-06.mp4

Is there a way to force refresh of intellisense as a band-aid?

**Comment by DustinCampbell** [comment]
This issue has been fixed in the 1.14 milestone. We just released our [first beta of 1.14](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.14.0-beta1) if you're interested in giving it a spin. Follow [these instructions](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases) to a beta release of C# for VS Code.
