### ISSUE TITLE
The limit of 'FormattingOptions'

### ISSUE THREAD

**Issue by Tezika** [OmniSharp/omnisharp-vscode#1682]
## Environment data
`dotnet --info` output:
VS Code version: 1,14.2
C# Extension version:1.110

## Expected  behavior
Hi,
The OmniSharp is a very awesome extension for VS Code. I love it and use it for my CSharp coding.However, when I wanna customize my formatting options, the options are limited.For instance, I wanna **insert the space within the control and flow statement keyword(`for( _ int i = xx; i < xx; i++ _ )`)just like the Visual Studio does. Unfortunately, I can't do that due to the limit of the 'FormattingOptions'(Only a property, "SpaceAfterControlFlowStatementKeyword", can change **the control  and flow statement** formatting.Thus, I guess that releasing more options provided for us to set seems helpful.)

Thanks,

**Comment by DustinCampbell** [comment]
Hi! C# for Visual Studio Code uses the same formatting engine that Visual Studio does and, barring any bugs, the options available should be the same. Although, an option's name might be different than what appears in Visual Studio's option UI. [OmniSharp's formatting options](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Workspaces/Formatting/CSharpFormattingOptions.cs) map specifically to the [C# formatting options API](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Workspaces/Formatting/CSharpFormattingOptions.cs) in Roslyn.

Consider the following options from Visual Studio 2017:

![image](https://user-images.githubusercontent.com/116161/28923097-aba39058-7811-11e7-948a-3b3620c8379a.png)

Using an 'omnisharp.json', you could map the options called out in the picture above like so:

```JSON
{
    "FormattingOptions": {
        "SpaceAfterControlFlowStatementKeyword": true,
        "SpaceWithinExpressionParentheses": false,
        "SpaceWithinCastParentheses": false,
        "SpaceWithinOtherParentheses": false,
        "SpaceAfterCast": false,
        "SpacesIgnoreAroundVariableDeclaration": false
    }
}
```

The option you want to set is `SpaceWithinOtherParentheses`. It looks like this is simply poorly named in Roslyn, because it only ever [applies to control flow statements](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Workspaces/Formatting/Rules/SpacingFormattingRule.cs,141) during formatting.
