### ISSUE TITLE
Intellisense not working with partial class

### ISSUE THREAD

**Issue by snormand** [OmniSharp/omnisharp-vscode#1685]
## Steps to reproduce
I did a dbcontext scaffold like the following commande.

dotnet ef dbcontext scaffold "server=LOCALHOST\SQLEXPRESS;Integrated Security=SSPI;database=SoPro" "Microsoft.EntityFrameworkCore.SqlServer" --schema dbo -d -f -c DbCtx -s ..\Web\Web.csproj

I do use a different projet for my BD.  So I used the -s parameter to do the scaffolding.

The output of this scaffolding create class like this.
`
namespace BD
{
    public partial class Contact
    { ... }
}
`

When I try to declare an instance of this class in my Web project (different projet), the BD.Contact class do not appear in then intellisense.  But the projet compile correctly with the command "dotnet build".

If I remove the "Partial" keyword in the class declaration, the intellisense work perfectly.

Thanks.

## Environment data
`dotnet --info` output:
.NET Command Line Tools (2.0.0-preview2-006497)

Product Information:
 Version:            2.0.0-preview2-006497
 Commit SHA-1 hash:  06a2093335

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview2-006497\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25407-01
  Build    : 40c565230930ead58a50719c0ec799df77bddee9

VS Code version: 1.14.2
C# Extension version: 1.11.0

**Comment by DustinCampbell** [comment]
I'm not familiar with using the ef command or setting up dbcontexts, but I think this is what you are describing:

1. You have your project open in VS Code.
2. You execute the `dotnet ef` command at either the command line or the terminal window in VS Code. It sounds like this generates a new file on a disk that adds a partial type.
3. In an existing file in your project, you try using that type and it doesn't appear in IntelliSense.
4. You open the file and remove the "partial" keyword. Then, going back to the file you were just in, you try using that type again and it does appear in IntelliSense.

Is the above a fair description of what you're seeing? If so, I _suspect_ the behavior may be by design.

Essentially, C# for VS Code won't "discover" that a new file has been added until you open it in an editor and actually make a change to it. You can verify that this is what you are seeing by trying a couple of things.

1. Try your repro again. But, instead of opening the generated file and removing the "partial" keyword, try running the `Restart OmniSharp` command or restarting VS Code. If I'm correct, I would expect the type to appear in IntelliSense once OmniSharp or VS Code is restarted.
2. Try your repro again. But, instead of removing the "partial" keyword, just make _any_ edit to the file.

If neither of these work, it sounds like my assumptions are wrong. :smile: In that case, I'll want to dig deeper.

**Comment by snormand** [comment]
As you suggested, I opened a file and simply edit and it worked.

Thanks!
