### ISSUE TITLE
.NetFramework4.6.1 projects referencing .NetStandard2.0 shows error message

### ISSUE THREAD

**Issue by cilerler** [OmniSharp/omnisharp-vscode#1736]
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

VS Code version:
![image](https://user-images.githubusercontent.com/385958/29670293-3dbd5354-88b4-11e7-8fae-6d3eb74110f4.png)

C# Extension version:
![image](https://user-images.githubusercontent.com/385958/29670360-7399638c-88b4-11e7-8db8-203f96e7f89f.png)

## Steps to reproduce
> You may use the repo [here](https://github.com/cilerler/nf461-ns2)

or if you would like to do it yourself please follow the steps.

1. Create completely new **.NET Framework 4.6.1** _class_ library.
2. Add **Microsoft.Extensions.DependencyInjection.Abstractions 2.0.0** package into it.  _(which will also add  **NETStandard.Library 2.0.0** and **Microsoft.NETCore.Platforms 2.0.0** packages)_
3. Add code below into empty **Class1.cs**

    ```csharp
	private readonly IServiceProvider _serviceProvider;

	public Class1(IServiceProvider serviceProvider)
	{
		_serviceProvider = serviceProvider;
	}

	public void Run()
	{
		var obj = _serviceProvider.GetService<object>();
		Console.ReadLine();
	}
    ```

## Expected  behavior
1. No error mark with red underline
2. Proper intellisense support

## Actual behavior

`dotnet msbuild` builds the project, however VSCODE shows the error 

```
The type 'IServiceProvider' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
```

![image](/cilerler/nf461-ns2/raw/master/docs/assets/2017-08-18_13-37-11.png)

**Comment by DustinCampbell** [comment]
I took a look at the repo and noticed that you're using a package.config file to manage your NuGet packages which the .NET Core SDK really doesn't support. For example, if you clone your repo and try `dotnet restore`, it'll print the message: `Nothing to do. None of the projects specified contain packages to restore.` Then, invoking `dotnet msbuild` will fail because packages are missing.

I might be wrong as I haven't looked deeply, but I _suspect_ the issue is that the NuGet support for handling packages.config in MSBuild is contained within VS 2017 and not the .NET Core SDK. I found that if open the project in VS 2017, NuGet restores and the project can build fine. If I then launch VS Code from a standard CMD prompt, I see the error message you described. In this case, we only use the MSBuild toolset that is included with C# for VS Code, which just looks for the .NET Core SDK. However, if I launch from a VS 2017 Developer Command Prompt, your project works fine because the MSBuild toolset is used from VS 2017.

If you launch VS Code from a VS 2017 Developer Command Prompt, does your project work in VS Code?

**Comment by cilerler** [comment]
Thank you Dustin, I understand it much better now how things work. 🤗 

Yes it does working when I run it from the _VS 2017 Developer Command Prompt_.

Since the initial project is _.Net Framework 4.6.1_ I need to use **packages.config** and I believe this will be a common usage for many people for a while.  But I don't mind to use it with the workaround you suggested. 

On the other hand, it may be a good thing to provide same _MSBuild_ toolset that used in _VS2017_ with the _C# for VS Code_ extension if possible.

**Comment by DustinCampbell** [comment]
> On the other hand, it may be a good thing to provide same MSBuild toolset that used in VS2017 with the C# for VS Code extension if possible.

There are several problems with doing this. The biggest issues are that the size would be extreme (another ~75 MB), it isn't cross platform, and it would get out of sync quickly. The general philosophy of C# for VS Code is to live SxS with the tools that it needs to build your project. If those tools are available, it should use them. In this case, I think it should do a better job of locating VS 2017 on your machine without you needing to launch it from a Developer Command Prompt. I _suspect_ it might have failed to find the installed VS 2017 because you have multiple VS 2017 instances installed. Is that the case? cc @AndyGerlicher  and @rainersigwald as FYI.

> Also, that issue doesn't happening if I open full .Net Framework 4.6.1 project which makes me wonder if this is something that needs to be fixed in MSBuild toolset in .NET Core SDK.

This is where I'd rather see things go. The .NET Framework support in the .NET Core SDK could definitely be more robust. If that were to happen, things would "just work".

**Comment by cilerler** [comment]
>  If those tools are available, it should use them. In this case, I think it should do a better job of locating VS 2017 on your machine without you needing to launch it from a Developer Command Prompt.

👍 that would be GREAT!

> I suspect it might have failed to find the installed VS 2017 because you have multiple VS 2017 instances installed. Is that the case?

Nope, but have SSMS _(not sure if it is related but since it depends on IDE, you may want to be aware)_

**Comment by rainersigwald** [comment]
@cilerler can you run this and let me know the results?

```
"c:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -all -prerelease
```

**Comment by cilerler** [comment]
```
Visual Studio Locator version 2.0.2 [query version 1.11.2331.64267]
Copyright (C) Microsoft Corporation. All rights reserved.

instanceId: 44fff173
installDate: 1/6/2017
installationName: VisualStudio/15.3.2+26730.10
installationPath: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise
installationVersion: 15.3.26730.10
isPrerelease: 0
displayName: Visual Studio Enterprise 2017
description: Microsoft DevOps solution for productivity and coordination across teams of any size
enginePath: C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service
layoutPath: C:\Users\ciler\AppData\Local\Temp
channelId: VisualStudio.15.Release
channelPath: C:\Users\ciler\AppData\Local\Microsoft\VisualStudio\Packages\_Channels\4CB340F5\catalog.json
channelUri: https://aka.ms/vs/15/release/channel
releaseNotes: https://go.microsoft.com/fwlink/?LinkId=660469#15.3.26730.10
thirdPartyNotices: https://go.microsoft.com/fwlink/?LinkId=660485
```

**Comment by rainersigwald** [comment]
Thanks! SSMS isn't the problem, then: it's https://github.com/Microsoft/msbuild/issues/2369.

**Comment by cilerler** [comment]
Great to hear that, not sure what I'm looking for.
It looks like Microsoft/msbuild#2454 merged 2 days ago, so is this mean it should be deployed soon?

**Comment by DustinCampbell** [comment]
FWIW, the code flow can take awhile. It'll also need to be deployed to an official build that OmniSharp can consume and them pulled into C# for VS Code.

**Comment by DustinCampbell** [comment]
Thanks for pointing me at that issue @rainersigwald -- that's super helpful!

**Comment by cilerler** [comment]
I guess there is nothing else we can do at this point therefore closing the issue.
I appreciate both of your help.  Thank you @rainersigwald & @DustinCampbell 🤗
