### ISSUE TITLE
net debugger warning

### ISSUE THREAD

**Issue by chrmarti** [OmniSharp/omnisharp-vscode#1784]
_From @HawkenKing on October 7, 2017 7:21_

- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-05T06:07:51.906Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.12.1

(1 theme extensions excluded)

---

Steps to Reproduce:

1. open VScode on El Capitan
2. get warning

Hi, I'm not sure how to get rid of this warning. I am using Unity and VScode, in their vanilla states.

This is something that appears in VScode after installing.

Any advice on how to stop this warning from appearing would be appreciated. 
![screen shot 2017-10-07 at 4 15 24 pm](https://user-images.githubusercontent.com/5999766/31305719-7a4f650c-ab7b-11e7-9524-836465841c9d.png)

_Copied from original issue: Microsoft/vscode#35781_

**Comment by gregg-miskelly** [comment]
@HawkenKing: Are you using .NET Core? Or some other form of C# (ex: Unity, Xamarin)?

**Comment by HawkenKing** [comment]
Hi @gregg-miskelly I'm not sure, I'm using whatever came with VScode and Unity.

Is there a way I can check?

**Comment by gregg-miskelly** [comment]
Based on your last comment, it sounds like you are trying to do Unity development, is that correct? If so, you installed the .NET Core SDK yourself?

**Comment by HawkenKing** [comment]
I've been installing VSCode since it was first available for mac to use with Unity (since 2015?), is the .NET core installation part of this process? Or Unity installation?

**Comment by gregg-miskelly** [comment]
I would be very surprised if either of those installed it. The C# extension will suggest installing it (so you can do .NET Core development), so that would be my guess as to how you got it.

My suggestion:
1. Go to your VS Code preferences file and add -- `"csharp.suppressDotnetInstallWarning": false`
2. Remove the .NET Core CLI

I am not sure if the .NET CLI team has fixed this yet, but at least for older versions of the .NET CLI (which is what you have installed as your OS is too old for new versions), there is no easy uninstaller. So here are some manual steps. You might want to move things into a backup directory instead of removing them in case something really is using the old CLI, though that seems unlikely --

```
# delete the dotnet folder under /usr/local/share/dotnet
1. cd /usr/local/share/dotnet && ls
2. sudo rm -rf dotnet

# delete the dotnet reference file at /etc/paths.d/dotnet
1. cd /etc/paths.d && ls
2. sudo rm dotnet
```
