### ISSUE TITLE
Attribute parameters and intellisense

### ISSUE THREAD

**Issue by Siccity** [OmniSharp/omnisharp-vscode#1814]
Expected behavior similar to current method behavior

![image](https://user-images.githubusercontent.com/6402525/32123458-8be67fb4-bb64-11e7-9e04-47e558185cd3.png)
Current behavior does not show any intellisense suggestions or information regarding the parameters of an attribute constructor

![image](https://user-images.githubusercontent.com/6402525/32123677-6734779c-bb65-11e7-952a-db1ae0a113f7.png)

Attribute should be displaying something along the lines of
`TestAttribute(int value)`

**Comment by DustinCampbell** [comment]
This issue has been fixed in the 1.14 milestone. We just released our [first beta of 1.14](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.14.0-beta1) if you're interested in giving it a spin. Follow [these instructions](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases) to a beta release of C# for VS Code.
