### ISSUE TITLE
${workspaceRoot} in launch.json cannot contain a space

### ISSUE THREAD

**Issue by thecodejunkie** [OmniSharp/omnisharp-vscode#184]
Hi,

I noticed today that if I try and debug an, application that is in a path that contains a space, it will fail. The reason is that as soon as it contains a space, everything to the right of the space is trimmed from the path, leaving it to execute on the wrong path

For example I've put a simple repo application in `c:\test app` and when I attempt to debug it, this what will be in the debug output

```
No executable found matching command "dotnet-c:\test"
The program 'c:\test app\bin\Debug\netcoreapp1.0\test.dll' has exited with code 1 (0x00000001).
```

remove the space and it works just fine.

This is what I have in my `launch.json` for a simple console app

```json
{
    "name": ".NET Core Launch (console)",
    "type": "coreclr",
    "request": "launch",
    "preLaunchTask": "build",
    "program": "${workspaceRoot}/bin/Debug/netcoreapp1.0/test.dll",
    "args": [],
    "cwd": "${workspaceRoot}",
    "stopAtEntry": false
},
```

I'm running `Visual Studio Code - Insiders` build with [omnisharp-vscode v1.0.1-rc2](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.0.1-rc)

```
$ dotnet --info
.NET Command Line Tools (1.0.0-rc2-002376)

Product Information:
 Version:     1.0.0-rc2-002376
 Commit Sha:  9d71cce383

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by gregg-miskelly** [comment]
I fixed this in post rc2 release builds.

**Comment by thecodejunkie** [comment]
Any deadline on the next release?

**Comment by gregg-miskelly** [comment]
Unfortunately it is outside of our control - there are a whole bunch of different projects (CoreCLR, CoreFX, .NET CLI, ASP.NET, VS Tooling, us, and the list goes on and on) that all need to go out together for rc2. Because there are so many projects, and because there are so many changes between rc1 and rc2 so none of the projects are at all independent, it means that the C# extension team doesn't get to decide when we ship, and it also means that the C# extension needs to avoid churn to make sure we aren't risking the overall release.

The good news is that ~1-2 weeks after rc2 ships, we plan to ship again to fix all the issues we weren't able to fix in the rc2 release. The fix for this will ship then.

**Comment by thecodejunkie** [comment]
I think I might just be confusing things here, I was thinking that this was a fix in `omnisharp-vscode` that puts our [releases](https://github.com/OmniSharp/omnisharp-vscode/releases) every now and then. But is this fix in the VSCode debugger package that is downloaded extra the first time you open a `.cs` file?

**Comment by gregg-miskelly** [comment]
Correct.
