### ISSUE TITLE
Bad refactoring proposal on stopwatch object

### ISSUE THREAD

**Issue by Xarkam** [OmniSharp/omnisharp-vscode#1886]
## Environment data
`dotnet --info` output:
```
Product Information:
 Version:            2.0.3
 Commit SHA-1 hash:  eb1d5ee318

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  17.10
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/2.0.3/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.3
  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df
```
VS Code version:
`1.18.1`

C# Extension version:
`1.13.1`
## Steps to reproduce
Make this code:
```
Stopwatch watch = new Stopwatch();
watch.Start();
Console.WriteLine("hello world:!");
watch.Stop();
```
Place you cursor on watch variable declaration and click to the lamp icon to show omnisharp refactoring proposition

## Expected  behavior
No proposing to make inline temporary variable if it's stopwatch object

## Actual behavior
Propose to refactoring in inline temporary variable, but it's bad because it's make two different stopwatch object.

**Comment by DustinCampbell** [comment]
Thanks for the feedback! The same behavior is exhibited in Visual Studio 2017, with which we share the same Roslyn refactoring engine.

In general, the Inline Temporary Variable refactoring is designed to be available as often as possible. Often, a refactoring can be invoked as a stepping stone to a larger change, and blocking the refactoring until the conditions for performing are perfect can feel restrictive. (In Visual Studio, this can be spotted by the user because a live preview is shown before a refactoring is invoked.)

**Comment by Xarkam** [comment]
Thanks. 
I did not know that Omnisharp was using roslyn

I use also vs2017 but with resharper, so I have the proposals to resharp :)

I would be more careful when I use vscode.
