### ISSUE TITLE
Support for source link and Microsoft symbol server

### ISSUE THREAD

**Issue by yhvicey** [OmniSharp/omnisharp-vscode#1935]
Will this extension support source link and Microsoft or other symbol server?

**Comment by gregg-miskelly** [comment]
SourceLink support is coming. This is tracked with https://github.com/OmniSharp/omnisharp-vscode/issues/373.

Some form of Symbol Server support will also eventually come. This is probably a bit further down the line as Microsoft is still trying to figure out a good story for publicly distributing Portable PDBs. Currently the official Microsoft symbol server only serves Windows PDBs, and since this extension doesn't support Windows PDBs, supporting it doesn't make much sense.
