### ISSUE TITLE
Ctrl-click GTD shows up on `get` keyword

### ISSUE THREAD

**Issue by rchande** [OmniSharp/omnisharp-vscode#1949]
## Environment data
`dotnet --info` output:
VS Code version: 
Version 1.20.0-insider
Commit f9115349ef09cfef2bed669680d10ac58b490dce
Date 2017-12-21T16:36:58.030Z
Shell 1.7.7
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
C# Extension version: 1.13.1

## Steps to reproduce
Hold control key and hover over `get`

## Expected  behavior
Get keyword is not hyperlinked

## Actual behavior
Get keyword is turned into a hyperlink

![image](https://user-images.githubusercontent.com/3751401/34529948-6fbecf34-f062-11e7-835e-54f17228abde.png)

**Comment by rchande** [comment]
This was fixed recently in Roslyn. @akshita31 do you want to take a look?

**Comment by akshita31** [comment]
This issue has been fixed in the 1.14 milestone. We just released a beta of 1.14 - https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.14.0-beta4. Follow [these instructions](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases) to install a beta release of C# for VS Code.
