### ISSUE TITLE
put open brackets on same line as construct in reformat code?

### ISSUE THREAD

**Issue by ciel** [OmniSharp/omnisharp-vscode#203]
I love the way the OmniSharp extension can let you format C# code, but is it possible to change the configuration such that open braces are on the same line as the construct? It keeps knocking mine down to the next line.

**Comment by jaybeecave** [comment]
I would really like this to, been trying all day to figure out how to do this

**Comment by ciel** [comment]
any kind of notice on this? is it even in the works or a desired feature?

**Comment by koppert** [comment]
+1

**Comment by DustinCampbell** [comment]
Yes! Controlling all of the C# formatting options exposed within Visual Studio is now possible due to https://github.com/OmniSharp/omnisharp-roslyn/pull/649. You can add an omnisharp.json file that includes the following:

```JSON
{
    "formatting": {
        "newLinesForBracesInMethods": false
    }
}
```

You can see the options available here: https://github.com/OmniSharp/omnisharp-roslyn/blob/dev/src/OmniSharp.Abstractions/Options/FormattingOptions.cs.
