### ISSUE TITLE
Add option to disable "some projects had problem opening" warning popup

### ISSUE THREAD

**Issue by johnkors** [OmniSharp/omnisharp-vscode#2110]
In the latest version of VS Code, where the alerts are shown in the bottom right, I seem to get a stupid amount of these during a re-build.

"Some projects have trouble loading. Please review the output for more details."
"Some projects have trouble loading. Please review the output for more details."
"Some projects have trouble loading. Please review the output for more details."
.
.
.
.
Did we have a way of disabling this message? It's showing 10 times during a build, and it's annoying the life out of me.

It's trying to warn me about using 4.6.1 references in a netcoreapp2 project (which I know might blow up, but I'm aware of the consequences and what I'm doing here).

```
[warn]: OmniSharp.MSBuild.ProjectLoader
        Package 'FluentMigrator.Runner 1.6.2' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.
```

Any way I can either disable all omnisharp popups or this ProjectLoader WARN in particular?

**Comment by rchande** [comment]
@johnkors This is a good feature request--thanks for filing.

**Comment by johnkors** [comment]
Can I ask in general - why are many of these OmniSharp WARNs turning into a _pop-up_? Pop-ups are so intrusive in the UI. In full blown Visual Studio they are kept in the debug log/ error log, which one can look into if one wants.

**Comment by rchande** [comment]
@johnkors There were no changes in the extension. VS Code changed how they display notifications (https://code.visualstudio.com/updates/v1_21#_new-notifications-ui). I would recommend filing bugs in [their repo ](https://github.com/Microsoft/vscode) with feedbac.

**Comment by johnkors** [comment]
Right, it changed from the top center, to bottom right. But it's still OmniSharp triggering the pop-ups.

**Comment by JohnAnthony** [comment]
The Visual Studio Code guys blame OmniSharp, and the OmniSharp guys blame Visual Studio Code.

https://github.com/Microsoft/vscode/issues/22702

**Comment by DustinCampbell** [comment]
@JohnAnthony : It's not about blame -- it's about bugs getting to the right people. The issue you linked is clearly a situation where an issue was filed on the main VS Code repo that was clearly meant for the C# extension for VS Code.

@johnkors : In the meantime, did you know that a single ESC key press can dismiss all of the popups?

**Comment by JohnAnthony** [comment]
@DustinCampbell I mean "blame" in the purely clinical sense. In the sens that one project has to be to blame, and we need to know which to correctly report this bug. @rchande has left directions to another project, but that project redirects back here.

As far as I can tell, `suppressDotnetInstallWarning` is being passed into `src/coreclr-debug/activate.ts` in the plugin (powered by OmniSharp) but is being ignored. The pop-up behaviour is questionable, but I believe the bug is here.

**Comment by rchande** [comment]
@JohnAnthony There are 2 separate complains being discussed here. One belongs to omnisharp and one to vscode:
* OmniSharp displays many notifications about warnings encountered while loading a project 
* VS Code notifications moved to a new location

For discussion of the particular notifications displayed by omnisharp, we're happy to take feedback and make changes accordingly. However, we don't have much control over the VS Code notification UX. Feedback on how that UX looks and where it appears/how large it is should go in the VS Code repo.

Sorry for any confusion!

**Comment by johnkors** [comment]
@rchande Sorry if this was unclear in my OP, but this issue is not with the _location_ of the pop-up. It's with the pop-ups presence in the first place. I don´t care it was moved from top center to bottom right. I care with the frequence of which I have to hit ESC to get rid of pop-ups that really are build/restore WARNs. This WARN msg could easily have been put into the build log instead of a pop-up, similarly to what VS does. 

@DustinCampbell Yeah, I'm aware of ESC closing pop-ups. I just don't get why OmniSharp _has_ to push this in my face. Or why I need to hit ESC this often at all. 

This is the second issue I've raised with OmniSharp pushing pop-ups in VS Code for no real good reason (imo). Am I really the only one finding pop-ups as a concept of feedback really intrusive? A pop-up should be last resort imo (ERROR/FATAL).

**Comment by DustinCampbell** [comment]
@johnkors: A big part of the problem here is that there's no way to really tell whether a warning or error that occurs during project load is fatal or not. I agree that it's probably OK to provide an option to disable this particular popup. However, setting that can hide the popup in cases where it's more meaningful for you. In that scenario, you might find (for example) that IntelliSense simply stops working, leaving you scratching your head.

**Comment by DustinCampbell** [comment]
@JohnAnthony: We're talking about different messages here.

There is an existing `suppressDotnetRestoreNotification` which suppresses messages that we display when your project changes in such a way that `dotnet restore` needs to run -- e.g. because you add a package reference to a project file or run `git clean -xdf` at the command line.

This issue is around the `Some projects have trouble loading. Please review the output for more details.` message that is display when MSBuild reports a warning or error when loading a project. There is no option to disable this. So, this issue tracks the feature request to add it.

**Comment by johnkors** [comment]
Thanks for explaining, @DustinCampbell . I get why you'd want to default to showing messsages as clear as possible to the user. So, when you don't know what the loglevel of the message is - you default to a pop-up, if I understood you correctly. 

Personally, I prefer to get feedback in the "Problems" / "Output" sections of VS Code than something I have to focus with a mouse, then click ESC. 

Maybe it could be a feature to select where to get these error messages? 

`omnisharp.feedback : "pop-up|output"`.

**Comment by tewarid** [comment]
For whoever lands here looking for an answer, add the following to user settings

```json
"omnisharp.disableMSBuildDiagnosticWarning": true
```
