### ISSUE TITLE
Intellisense doesn't understand inheritance

### ISSUE THREAD

**Issue by mistergreen** [OmniSharp/omnisharp-vscode#2215]
VS Code version: 1.22.2, OSX
C# Extension version: 1.14.0

## Steps to reproduce
Make an inherited class

`public class SpaceShip : EnemyController`

## Expected  behavior
The type or namespace name 'EnemyController' could not be found (are you missing a using directive or an assembly reference?) [Assembly-CSharp-firstpass]

Error will go away when I quit and relaunch VSCode.

**Comment by DustinCampbell** [comment]
Hey @rchande, this seems to be another repro of the problem where adding new files aren't picked up right away.

**Comment by rchande** [comment]
@mistergreen There were a number of fixes for this in 1.15. Can you try upgrading to 1.15 and see if that resolves the issue for you?

**Comment by mistergreen** [comment]
Nope, the issue is still there.

> The type or namespace name 'EnemyController' could not be found (are you missing a using directive or an assembly reference?) [Assembly-CSharp-firstpass]

**Comment by SirIntruder** [comment]
The problem is not that files aren't picked up right away, problem is that they were picked by the wrong project (SpaceShip should be in Assembly-CSharp.csproj instead of Assembly-CSharp-firstpass.csproj, but o# doesn't know that). 

Omnisharp code which handles new files is BufferManager.FindProjectsByFileName, it carpet bombs new files to all of the projects in first folder with projects. Unity keeps all projects in project root, so these issues happen.

https://github.com/OmniSharp/omnisharp-roslyn/blob/7e684d4a7c8d0ca29313fb19b267dfc121c3cd73/src/OmniSharp.Roslyn/BufferManager.cs

**Comment by mistergreen** [comment]
Yes, this for for Unity.
Thanks for letting me know where to look. Newly created file doesn't show up in the xml in Assembly-CSharp.csproj if that's the problem. Something curious also. I delete a file and it's still in Assembly-CSharp.csproj.

I open the project up in VS Community, created a new file and it works fine. The project is all under Assembly-CSharp.

**Comment by DustinCampbell** [comment]
@mistergreen : C# for VS Code won't modify your project file at all. So, if you add files, you'll need to ensure they're listed in the project file. After changing the project file, be sure to restart OmniSharp.
