### ISSUE TITLE
OmniSharp - "latest" is being downloaded on every restart

### ISSUE THREAD

**Issue by akshita31** [OmniSharp/omnisharp-vscode#2253]
The install test path ends with mono.linux-x86 which is not present in the latest OmniSharp versions, hence the package is being downloaded on every restart of the server when the omnisharp path is set to "latest".

@TheRealPiotrP @DustinCampbell @rchande @colombod

**Comment by DustinCampbell** [comment]
We determined in email that this is likely due a change in the OmniSharp packaging for OSX, Linux-x86 and Linux-x64 where the Mono runtime has moved to a "bin" folder. I suspect that an appropriate fix would be to just test the presence of the "run" script, since that's the thing that should be launched.

**Comment by akshita31** [comment]
This will be fixed once the release (specifically this commit - https://github.com/OmniSharp/omnisharp-vscode/commit/81df57cff148edcf4f53819ee19ceec4cbdd5966) will be merged into master

**Comment by DustinCampbell** [comment]
@akshita31: I built a VSIX from the release branch and it still tries to download the latest every restart.
