### ISSUE TITLE
¿Is it possible to debug a Service Fabric application?

### ISSUE THREAD

**Issue by felipecruz91** [OmniSharp/omnisharp-vscode#2264]
¿Is it possible to debug a Service Fabric application? I would like to be able to deploy a Service Fabric app to my local SF Cluster using Visual Studio Code.

**Comment by gregg-miskelly** [comment]
There isn't any way, that I am aware of at least, to launch a service fabric app under a debugger with VS Code. Service Fabric requires a pretty complicated orchestration between the IDE and the Service Fabric Runtime so that new processes get launched and then the debugger is immediately asked to attach to them.

The only thing that I would expect to work is that you could manually attach to an individual Service Fabric worker process.

**Comment by felipecruz91** [comment]
Thanks for the answer 👍
