### ISSUE TITLE
Add option to restore all projects in solution

### ISSUE THREAD

**Issue by akshita31** [OmniSharp/omnisharp-vscode#2276]
In reference to : https://github.com/OmniSharp/omnisharp-vscode/issues/240

I propose the following change:
.NET: Restore All Projects : Restore all the projects in the workspace.
.NET Restore Project: Shows a command palette menu to select one of the projects to be restored.

How does that sound ?

Also we have a 'There are unresolved dependencies..' warning that pops up for every project that has an unresolved dependency. How do we change that? It is irritating especially when there are a number of projects in the solution. Should we modify that to come up when there is atleast one project that has an unresolved dependency 
`There are unresolved dependencies in the solution. Please execute the restore command to continue.`
and then when the user clicks restore we perform the 'Restore all projects' as stated above ?

**Comment by akshita31** [comment]
Please share your thoughts @rchande @TheRealPiotrP @DustinCampbell

**Comment by rchande** [comment]
@akshita31 I'm on board for having two commands for restoring projects. I don't have strong opinions about the names of those commands. I completely agree with your solution for the warning. It's annoying because we show one notification per project. The clear solution (as you said) is to only show one notification that offers to restore all projects. I'm having trouble imagining scenarios where users would want to only restore a subset of projects in response to the warning.

**Comment by DustinCampbell** [comment]
FYI that there's also this: https://github.com/OmniSharp/omnisharp-vscode/issues/240
