### ISSUE TITLE
[Suggestion] Show bulb items in the <right click> menu

### ISSUE THREAD

**Issue by jeffschwMSFT** [OmniSharp/omnisharp-vscode#231]
![blub](https://cloud.githubusercontent.com/assets/9561583/14718624/9b242f5c-07ac-11e6-910e-420fdd33a34f.gif)

I like the options that the lightbulb offers, though I often find myself right clicking to "add method body" as opposed to hovering over and clicking on the lightbulb.  Is it possible to (in addition to the lightbulb) show those items in the <right click> menu?  Coming from VS this muscle memory is hard to break.

C# Extension 1.0.3-rc2
OS X

**Comment by DustinCampbell** [comment]
I think this is probably an issue for VS Code itself. @chrisdias?

**Comment by chrisdias** [comment]
You should be able to press CMD+. (or Ctrl+. on Windows) to bring up the Quick Fix list instead of having to hover.

Having a set of refactorings be contributed to the context menu would be something that would be in VS Code and OmniSharp would contribute to that list. @DustinCampbell can you make an issue in the VS Code repo if you need this for the C# editing experience?

**Comment by DustinCampbell** [comment]
I don't think we're ultimately going to add specific refactorings and code fixes to the right-click menu.
