### ISSUE TITLE
Reformatting indents complete lambda expression

### ISSUE THREAD

**Issue by zEh-** [OmniSharp/omnisharp-vscode#2328]
Issue Type: <b>Bug</b>

Reformatting this results in moving the whole expression after "onOpenCallback" one space to the right instead of adding just one space.

THIS

```
onOpen += onOpenCallback= () =>
{
    // ...
};
```

BECOMES

```
onOpen += onOpenCallback[SPACE]= () =>
[SPACE]{
[SPACE]    // ...
[SPACE]};
```

Extension version: 1.15.2
VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.17134

**Comment by DustinCampbell** [comment]
That is definitely annoying. I can repro the same issue in Visual Studio 2017, so it looks like this is a Roslyn bug. I've filed https://github.com/dotnet/roslyn/issues/27025 to track the problem there. Once it's fixed in Roslyn, we can take the fix into OmniSharp and it will start working in C# for VS Code.
