### ISSUE TITLE
Packages from scriptcs_packages.config are ignored in editor

### ISSUE THREAD

**Issue by iamsap** [OmniSharp/omnisharp-vscode#2370]
- Extension Name: csharp
- Extension Version: 1.15.2
- OS Version: Windows_NT x64 10.0.14393
- VSCode version: 1.23.1

My C#Script program runs fine, but the editor complains about packages installed via NuGet unless I put a physical "#r" reference in the file.  I'd like to avoid putting assembly references in the file.  I would assume the package config would be used for this?  See screenshot below.

![vscode](https://user-images.githubusercontent.com/3976090/41122294-e8b52ebc-6a4f-11e8-9a1e-39a9f616fa8f.png)

**Comment by DustinCampbell** [comment]
cc @filipw

**Comment by filipw** [comment]
OmniSharp doesn't support scriptcs since 2016, see this PR for some background https://github.com/OmniSharp/omnisharp-roslyn/pull/659

If you'd like to use Nuget packages in scripting and get language services, you will either have to manually import the DLLs (like you already shown) or use [inline Nuget packages](https://github.com/filipw/dotnet-script#nuget-packages-1). In the second case though, scriptcs doesn't support that syntax so you'd need to use a runner that supports it, like `dotnet-script`.

Hope this helps.

**Comment by filipw** [comment]
I'll close this issue as there is nothing to do here - there is no plan to support this specific feature in the future. 🙂
If you have any further questions feel free to reopen or just comment.

**Comment by iamsap** [comment]
Thank you for your response @filipw
