### ISSUE TITLE
Same line curly braces for C#

### ISSUE THREAD

**Issue by jrieken** [OmniSharp/omnisharp-vscode#243]
_From @weshardee on April 23, 2016 2:44_

Is there or will there be a setting to toggle how curly braces are formatted in C# similar to https://github.com/Microsoft/vscode/issues/1533?

_Copied from original issue: Microsoft/vscode#5683_

**Comment by jrieken** [comment]
_From @dbaeumer on April 23, 2016 19:24_

@jrieken not sure if this would be us or OmniSharp.

**Comment by jonfreeland** [comment]
Any updates on this?

**Comment by DustinCampbell** [comment]
Yes! Controlling all of the C# formatting options exposed within Visual Studio is now possible due to https://github.com/OmniSharp/omnisharp-roslyn/pull/649. You can add an omnisharp.json file that includes the following:

```JSON
{
    "formatting": {
        "newLinesForBracesInMethods": false
    }
}
```

You can see the options available here: https://github.com/OmniSharp/omnisharp-roslyn/blob/dev/src/OmniSharp.Abstractions/Options/FormattingOptions.cs.

**Comment by hheexx** [comment]
If somebody ended on this issue from google as me:

I think syntax changed and snippet above does not work.
"formatting" should be changed to "FormattingOptions"

**Comment by filipw** [comment]
@hheexx correct. you can find more details in the blog post here http://www.strathweb.com/2017/01/c-code-formatting-settings-in-vs-code-and-omnisharp/

**Comment by colonelchlorine** [comment]
I'm still seeing same line curly braces in VSCode with Omnisharp. Tried setting that the FormattingOptions to both true/false and it still remains on the first line (tested with restart as well). Any ideas? @DustinCampbell

**Comment by DustinCampbell** [comment]
```JSON
{
    "FormattingOptions": {
        "newLinesForBracesInMethods": false
    }
}
```

works for me.

**Comment by santosh** [comment]
@DustinCampbell I'm not sure where to add these lines to. And shouldn't be it in the setting we use to go to with `Ctrl+,`?

**Comment by d0rf3n** [comment]
I just found the exact same problem as @santosh above.

The snippets for "if", "for", etc don't follow the formatting settings or something.

The code...
```
if (true)
{
    
}
```
...is created. And then when I format the document using format. It moves the braces to same line as if statement.

I also tried placing same FormattingOptions in a omnisharp.json file i both `HOME/.omnisharp/` and the project home. No difference.

**Comment by N3pp** [comment]
For those who also want to change the snippets:

Open
`%USERPROFILE%\.vscode\extensions\ms-vscode.csharp-1.15.0-beta3\snippets\csharp.json` or
`%USERPROFILE%\.vscode\extensions\ms-vscode.csharp-1.14.0\snippets\csharp.json` (for stable release)

then use "Find and Replace" (CTRL+H/F) with regex option enabled to replace
`",\n        ]"{"`
with
` {"`
then apply for all then restart OmniSharp with command palette.

Make sure to backup csharp.json after changing it because OmniSharp overwrites it on update.

@santosh @d0rf3n

**Comment by santosh** [comment]
@N3pp  There's no omnisharp folder in `%USERPROFILE%\.vscode\extensions\`, should I create one? If so, then by which name? Because extensions of that folder have version number embedded. I don't know which version of omnisharp version I'm using. 

My VS Code is up to date by the way.

**Comment by N3pp** [comment]
@santosh Mine is named "ms-vscode.csharp-1.15.0-beta3". It should be "ms-vscode.csharp-1.14.0" for the current latest stable release.
I didn't want to type the full path because extension folders include version numbers as you said so it'll be different depending on when people are going to read the post. But OmniSharp's folder doesn't have "omnisharp" in its name so I'll edit the post to make it more clear.

**Comment by d0rf3n** [comment]
Thanks a lot for this. I'll try it out later when I'm back home from
vacation.

@N3pp

**Comment by SolAZDev** [comment]
Sorry, FixFormat is removed from the marketplace... Could we **please** get this as an option?

**Comment by JoeRobich** [comment]
@SolAZDev The C# extension supports configuring your formatting and code style preferences from an .editorconfig file. Please see [the documentation here](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/code-style-rule-options) to see what the configuration options are. You may want to also enable "omnisharp.enableRoslynAnalyzers" in VS Code preferences to get even more fixes for your code style preferences.

**Comment by Vasdranna** [comment]
> [@SolAZDev](https://github.com/SolAZDev) The C# extension supports configuring your formatting and code style preferences from an .editorconfig file. Please see [the documentation here](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/code-style-rule-options) to see what the configuration options are. You may want to also enable "omnisharp.enableRoslynAnalyzers" in VS Code preferences to get even more fixes for your code style preferences.

Is there any way to set global settings instead of making a `.editorconfig` file each time?

**Comment by JoeRobich** [comment]
answered at https://github.com/dotnet/vscode-csharp/issues/6026#issuecomment-2546104450
