### ISSUE TITLE
Breadcrums are not working as good as typescript.

### ISSUE THREAD

**Issue by Jonatthu** [OmniSharp/omnisharp-vscode#2496]
vscode 1.27 (and 1.26 too) mac and windows

When I click the method name, breadcrums are just fine.
![image](https://user-images.githubusercontent.com/3742176/45175248-d418ce00-b1c1-11e8-96e5-bb5b5e4595da.png)

When I click inside the method the breadcrums is not in sync with the method name
![image](https://user-images.githubusercontent.com/3742176/45175293-f1e63300-b1c1-11e8-99d2-0333394e5e2b.png)

On typescript even if I am clicking in the body method is working fine.
![image](https://user-images.githubusercontent.com/3742176/45175409-3e317300-b1c2-11e8-83bd-706332afea1c.png)

I have created a bug on vscode repo as well
https://github.com/Microsoft/vscode/issues/58103

**Comment by akshita31** [comment]
@Jonatthu Thanks for filing the issue. With the extension version 1.15.2 it definetly reproduces. However I tried with the latest beta and seems that it is fixed in that one. We will be doing a release soon so probably this wont be present in that. 
If you are interested, you can try with the [latest beta]( https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.16-beta4). The instructions for installing it can be found [here](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases). 


![breadcrumbs](https://user-images.githubusercontent.com/12554141/45181091-40033280-b1d2-11e8-8006-2de4ce60de9b.PNG)

**Comment by Jonatthu** [comment]
@akshita31 Thanks! I am a huge fan of c# and vscode and I could not ignore this haha when my typescript is working as expected, I will wait for the release!

**Comment by akshita31** [comment]
@Jonatthu Any update here ?

**Comment by Jonatthu** [comment]
Now is working fine in 1.6! but there is a different issue that I already opened.

Sorry for the late response, and thanks !
