### ISSUE TITLE
Cannot run C# tests

### ISSUE THREAD

**Issue by denisvlah** [OmniSharp/omnisharp-vscode#2544]
## Environment data
.NET Core SDK:  2.1.401
 OS Name:     ubuntu 16.04
VS Code version: 1.27.1
C# Extension version: 1.16.1

## Steps to reproduce
1) Open folder in VSCode  with C# netcore solution.
2) Wait for OmniSharp to load completely.
3) Open xUnit test file

## Expected  behavior: 
Links Run|Debug should appear above each test method
## Actual behavior: 
Links Run|Debug don't appear.

It worked in previous version. Also it works on small projects.
The OmniSharp log is ok - no error messages.
At the same time the OmniSharp icon display that it has errors: 
![image](https://user-images.githubusercontent.com/12544479/45827150-83938b80-bcfe-11e8-8efb-ddcbb84e7eaf.png)

Also there are errors in Window log. 
I have also attached the VSCode Window log with errors:
[WindowLog.txt](https://github.com/OmniSharp/omnisharp-vscode/files/2401884/WindowLog.txt)

And OmniSharp log:
[OmniSharpLog.txt](https://github.com/OmniSharp/omnisharp-vscode/files/2401887/OmniSharpLog.txt)

**Comment by akshita31** [comment]
@denisvlah The red error flame is not because of omnisharp process crashing. It is because of a typical mono behavior and we have already fixed that in master: https://github.com/OmniSharp/omnisharp-vscode/pull/2540.

From your omnisharp log I don't see any error being printed. Since you are saying that it works on small projects, can you try "omnisharp.projectLoadTimeout" to a higher value and then "Ctrl+Shift+P --> Restart Omnisharp"?

**Comment by akshita31** [comment]
@denisvlah Any updates here ?

**Comment by denisvlah** [comment]
The OmniSharp doesn't timeout. Intelicence and code navigation and code suggestions works perfect, it just not show links to run tests.
Also I have tried it on Windows with the same solution and it worked.
Also a few words about solution - it has 2 .csproj files in the same folder. They are related to different solutions. One project is for netcore and the second one is for full framework.
On the Windows where I can run tests it display links but fails to run. It complaints that folder has 2 project files. If there is only 1 project file it works fine.

I will try to debug the C# extension when I will have time. To reproduce this issue you should have my solution files that I am not allowed to share.

**Comment by akshita31** [comment]
@denisvlah I can totally reproduce the problem.

More information:
In my developer console, I see that there was an error.
![image](https://user-images.githubusercontent.com/12554141/46689428-a9e97000-cbb4-11e8-83f6-85412329b16a.png)

We will get it resolved as soon as possible. Thank you for your patience.

**Comment by akshita31** [comment]
![image](https://user-images.githubusercontent.com/12554141/46689786-7a873300-cbb5-11e8-90ef-776ac55c0f9d.png)

There is an argument exception in the omnisharp process, due to which the codelens is not appearing.

**Comment by akshita31** [comment]
On investigating further, the line here is throwing the exception:
https://github.com/OmniSharp/omnisharp-roslyn/blob/fe68d63b16fb44b2e647f538ffd8b1ec95fabb0e/src/OmniSharp.Roslyn.CSharp/Services/Structure/CodeStructureService.cs#L365

Because it is adding two values for the same key -"testFramework" - xunit and nunit

**Comment by akshita31** [comment]
When I changed the namespace "NUnit.Framework" to "abc.Framework", everything works fine.

**Comment by denisvlah** [comment]
Closing this issue as it is very specific to the project I am working on and a better way to go is to refactor all tests to use NUnit3 with standard [Test] without additional hacks.
