### ISSUE TITLE
Any plans to extract the package manager?

### ISSUE THREAD

**Issue by Razzeee** [OmniSharp/omnisharp-vscode#2648]
Are there any plans to extract the package manager behaviour and make it available for other vscode integration? This part of the code https://github.com/OmniSharp/omnisharp-vscode/pull/2188

I'm also curious how these urls get created https://github.com/OmniSharp/omnisharp-vscode/commit/5f8d5c44603a1bf50777b7e565efed132c96c0d2 as I never pushed an extension to the store before. Or are these MS specific/self-hosted?

**Comment by gregg-miskelly** [comment]
Our hope is that someday the VS Code team provides a story for extensions having platform-specific dependencies so that our package manager code can go away. So I am somewhat hesitant to think we should pull it out into its own package. But regardless, you can certainly just copy/paste the code into your own extension.

VS Code provides no support for external dependencies, including there is no services that will host files to be downloaded. So you will need your own blob/CDN hosting solution for any files you need to download.

**Comment by Razzeee** [comment]
Thanks for your fast response :)

It's unfortunate that this is the case, as having a package would have been a better solution for me. But it's completely understandable. I will just copy everything we need then I guess.

One last question, I am correct, that you use this to download the language server implementation for the used platform? Just checking, as I'm not 100% sure.

**Comment by gregg-miskelly** [comment]
Correct: this is used to download the platform-specific language server (as well as the platform-specific debugger)
