### ISSUE TITLE
Visual Studio Code nuget packge from local source

### ISSUE THREAD

**Issue by mubarik** [OmniSharp/omnisharp-vscode#2677]
How can we consume Nuget package installed on local folder in Ubuntu 14.04 in visual studio code please.

**Comment by rchande** [comment]
@mubarik Generally speaking, you'll have to install the NuGet package by whatever mechanism your project uses. If you use dotnet core, you can `dotnet add` the package. The C# extension doesn't provide support for installing packages.

I'm closing this issue because it appears to be a question not specific to the C# extension. Feel free to file another issue if you find an issue related to our handling of NuGet package.
