### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Obscuriosity** [OmniSharp/omnisharp-vscode#2817]
[ms-vscode.csharp-unresponsive.cpuprofile.txt](https://github.com/OmniSharp/omnisharp-vscode/files/2799017/ms-vscode.csharp-unresponsive.cpuprofile.txt)

- Issue Type: `Performance`
- Extension Name: `csharp`
- Extension Version: `1.17.1`
- OS Version: `Linux x64 4.15.0-43-generic`
- VSCode version: `1.30.2`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/tony/ms-vscode.csharp-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by akshita31** [comment]
@Obscuriosity Thanks for filing an issue. We are working on it.

**Comment by akshita31** [comment]
@Obscuriosity  The [beta version](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.18.0-beta7) containing the fix for this issue is out. You can install it by following the instructions [here](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases).

We believe this would fix the issue. Please try it out.

**Comment by akshita31** [comment]
@Obscuriosity  We haven't heard back from you in a while so I will close this issue for now. Please feel free to reopen if the problem still persists.
