### ISSUE TITLE
can't debug netcore 2.2 on fedora 29

### ISSUE THREAD

**Issue by Jacfal** [OmniSharp/omnisharp-vscode#2840]
## Environment data
`dotnet --info` output:

```
NET Core SDK (reflecting any global.json):
 Version:   2.2.103
 Commit:    8edbc2570a

Runtime Environment:
 OS Name:     fedora
 OS Version:  29
 OS Platform: Linux
 RID:         fedora.29-x64
 Base Path:   /usr/lib64/dotnet/sdk/2.2.103/

Host (useful for support):
  Version: 2.2.1
  Commit:  878dd11e62

.NET Core SDKs installed:
  2.2.103 [/usr/lib64/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.NETCore.App 2.2.1 [/usr/lib64/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

VS Code version: 1.30.2
C# Extension version: 1.17.1

## Steps to reproduce
1.open c# code
2.add breakpoint
3.start debugging

## Expected  behavior
debugging (stop on breakpoint)

## Actual behavior

Debug adapter process has terminated unexpectedly (exit code: null)

Console debug:

```
-------------------------------------------------------------------
You may only use the Microsoft .NET Core Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.
-------------------------------------------------------------------
<- (R) {"seq":4,"type":"response","request_seq":2,"success":true,"command":"launch"}
<- (E) {"seq":5,"type":"event","event":"initialized","body":{}}
```

**Comment by gregg-miskelly** [comment]
@Jacfal Can you using the following instructions to see if anything more useful gets printed to the terminal?

https://github.com/OmniSharp/omnisharp-vscode/wiki/Enabling-C%23-debugger-logging#full-method

Also, did you install .NET Core via a package manager? If you try are run an ASP.NET Core app normally, does it run okay? The behavior you are seeing is what happens when .NET Core is missing one of its native dependencies, so that is my first guess, but maybe I am wrong as it doesn't really make sense in your case.

**Comment by Jacfal** [comment]
@gregg-miskelly You are right, problem was with missing dependencies. I installed dotnet from copr repository instead of using official repositories. Reinstalling dotnet from microsoft repository solved the issue. 

Thanks for pointing me in the right direction.
