### ISSUE TITLE
Generated launch.json doesn't fill out 'program' path if 'buildOptions' is used in project.json

### ISSUE THREAD

**Issue by dougbu** [OmniSharp/omnisharp-vscode#291]
###### VS Code experience
The default "program" value in the `.NET Core Launch (console)` and `.NET Core Launch (web)` configurations is `"${workspaceRoot}/bin/Debug/<path-to-program>"`. Since 90% of the time we'll be debugging a .NET Core app, this path should be more like `".../netcoreapp1.0/<path-to-program>"`.

Would be even better if the default value did not need tweaking at all. That is, use the name of the project (which OmniSharp should know) or add a variable like `${ProjectName}` and use `".../${ProjectName}.dll"`.

**Comment by gregg-miskelly** [comment]
@dougbu did you manually create the launch.json through this prompt:

![Info: Required assets to build and debug are missing from your project. Add them? Yes | Close](https://raw.githubusercontent.com/wiki/OmniSharp/omnisharp-vscode/images/info-bar-add-required-assets.png)

If yes - this is because we don't have an OmniSharp right now which is compatible the breaking change to project.json to rename 'compilationOptions' to 'buildOptions' we will be moving to a new version soon which should fix this.

If no - for our off road scenario, we want to try and make it a bit more clear what to do. So I am a little worried about automatically guessing what target framework is being used. That is certainly a reasonable guess, but I don't know what the future of these frameworks holds.

**Comment by dougbu** [comment]
@gregg-miskelly I used the automatically-provided `launch.json` file but updated it to use `"buildOptions"` because I saw the "deprecated" warning. Guess I must have made that `project.json` "fix" before generating the `launch.json` file.

**Comment by gregg-miskelly** [comment]
Thanks. I renamed your bug so it is more clear what this tracks. @DustinCampbell I am assigning this to you to resolve when you insert the new OmniSharp.

**Comment by DustinCampbell** [comment]
Thanks! Yes, this should be fixed once we update OmniSharp.

**Comment by dougbu** [comment]
@DustinCampbell what is the timeline for updating OmniSharp to handle the new `project.json` schema?

**Comment by DustinCampbell** [comment]
Very soon. We're working on a new OmniSharp release that we can pin the C# extension to right now.

**Comment by DustinCampbell** [comment]
This should fix the issue: https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.0.6-rc2

**Comment by gregg-miskelly** [comment]
@DustinCampbell did you verify, or would you like us to?
/cc @caslan

**Comment by DustinCampbell** [comment]
I'm moving quickly. I posted before verifying and about to try on my MacBook

**Comment by DustinCampbell** [comment]
yes, it works on OS X. `buildOptions` is now properly supported by the C# Extension. You can even change it back and forth between `compilationOptions` and `buildOptions`. IntelliSense continues working in either case.
