### ISSUE TITLE
"Generate type" context menu option does nothing

### ISSUE THREAD

**Issue by mellinoe** [OmniSharp/omnisharp-vscode#302]
![image](https://cloud.githubusercontent.com/assets/8918977/15159525/f221623c-16a9-11e6-9357-fa262bd124d2.png)

Selecting the "Generate type" option from this context menu does not do anything.

**Comment by five70apps** [comment]
Just keep in mind that the context menu shown in this issue is completely different from what I see with the configuration specified at #1119. The "Generate type" command is not present in the context menu (or I don't know how to access the context menu shown above).
![untitled](https://cloud.githubusercontent.com/assets/4247685/21943669/4975d75c-d9a0-11e6-9278-e9addf0c251a.png)

**Comment by DustinCampbell** [comment]
It appears that this is due to the fact that Roslyn code actions can now be nested. In VS, "Generate type" is the parent of a submenu of several code action options.
