### ISSUE TITLE
Codelens for tests only works for single test project in Solution

### ISSUE THREAD

**Issue by sudsy** [OmniSharp/omnisharp-vscode#3031]
If you create 2 test projects in a solution as described in this comment on #1934, the second project does not show CodeLens annotations for running the tests. I was able to reproduce this case in VsCode on MacOS

https://github.com/OmniSharp/omnisharp-vscode/issues/1934#issuecomment-450362167

**Comment by filipw** [comment]
Can you please describe step by step the repro scenario or provide a sample project with this behavior?
It is not entirely clear to me how this should be repro based on the linked description. The original issue was closed because the step to add a newly created project to the solution was missing which caused the behavior (OmniSharp would track the solution and new project didn't belong to the solution).

Thanks.

**Comment by sudsy** [comment]
No problem.

1. dotnet new sln -n CodeLensTest
2. Create test folder mkdir Test, cd ./Test
3. Create test project dotnet new xunit
4. Add project to solution dotnet sln ../CodeLensTest.sln add ./Test.csproj
5. Codelens annotations for Run Test and Debug Test appear on Scaffolded test method
6. Create second test folder mkdir Test2, cd ./Test2
7. Create test project dotnet new xunit
8. Add project to solution dotnet sln ../CodeLensTest.sln add ./Test2.csproj
9. build solution dotnet build CodeLensTest.sln
10. CodeLens annotations remain for test method in Test project but do not appear in Test2 project

**Comment by sudsy** [comment]
This problem was resolved after upgrading mono as identified in #3034
