### ISSUE TITLE
Downloads tools for .NET when trying to open launch.json for non-.NET project

### ISSUE THREAD

**Issue by inosik** [OmniSharp/omnisharp-vscode#3080]
## Issue Description ##

We did a workshop on React development at my company today. As I wanted to create a new `launch.json` file to set up the Chrome debugger, the C# extension got activated and started downloading OmniSharp, the .NET Core debugger and the Razor Language Server.

## Steps to Reproduce ##

1. Update the C# extension from an older version

    The extension has to download new versions of the .NET tools the next time.

1. Install the Chrome debugger extension

1. Start a new web project

1. Run the "Debug: Open launch.json" command and select Chrome

## Expected Behavior ##

A newly generated `launch.json` should be opened.

## Actual Behavior ##

The C# extension kicks in and starts downloading 150 MB worth of dependencies, even though my project has absolutely nothing to do with .NET.

### OmniSharp log ###

_Nothing to see here._

### C# log ###

_Note: The output is incomplete because I had to restart VS Code. My companies Wi-Fi stopped working for some reason._

<details>
Installing C# dependencies...
Platform: darwin, x86_64

Downloading package 'Razor Language Server (macOS / x64)' (57227 KB).................... Done!
Installing package 'Razor Language Server (macOS / x64)'

Finished
</details>

## Environment information ##

**VSCode version**: 1.34.0
**C# Extension**: 1.19.1

<details><summary>Mono Information</summary>
        OmniSharp using global mono :5.20.1</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   2.2.204
 Commit:    8757db13ec

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/dotnet/sdk/2.2.204/

Host (useful for support):
  Version: 2.2.5
  Commit:  0a3c9209c0

.NET Core SDKs installed:
  2.1.507 [/usr/local/dotnet/sdk]
  2.1.604 [/usr/local/dotnet/sdk]
  2.2.107 [/usr/local/dotnet/sdk]
  2.2.204 [/usr/local/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [/usr/local/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [/usr/local/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [/usr/local/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [/usr/local/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [/usr/local/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [/usr/local/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|ariake-dark|wart|0.2.2|
|backspace-plusplus|jrieken|0.0.17|
|bettergitcommits|davidedmiston|0.5.0|
|csharp|ms-vscode|1.19.1|
|debugger-for-chrome|msjsdiag|4.11.3|
|EditorConfig|EditorConfig|0.13.0|
|embrace|mycelo|1.0.0|
|Ionide-fsharp|Ionide|3.38.0|
|Ionide-Paket|Ionide|1.12.0|
|leaper|OnlyLys|0.5.3|
|mono-debug|ms-vscode|0.15.8|
|msbuild-project-tools|tintoy|0.2.54|
|nord-visual-studio-code|arcticicestudio|0.8.0|
|path-intellisense|christian-kohler|1.4.2|
|rewrap|stkb|1.9.1|
|spaces-inside-braces|AiryShift|0.4.0|
|subtle-brackets|rafamel|3.0.0|
|theme-light-vs-mac|jamiewest|0.4.5|
|vscode-cil-complete|wk-j|0.0.5|
|vscode-icon-theme|jtlowe|1.6.5|
|vscode-subword-navigation|ow|1.1.5|;

</details>

**Comment by gregg-miskelly** [comment]
Hi @inosik, there is currently nothing that the C# extension can do about this. The C# extension needs to register itself to provide launch.json templates, which means that when you ask for launch.json templates the C# extension will activate. In order to activate, we need to download our dependencies.

Two notes:
1. The VS Code team has a proposed feature to eliminate this problem (at least once the feature ships and the C# extension takes advantage of it): https://github.com/microsoft/vscode/issues/23251
2. You may already know this, but this is only a problem the first time you activate the C# extension following an update. The C# extension purposely doesn't update much because we know that the download experience for extensions with platform-specific dependencies isn't great.

**Comment by inosik** [comment]
Thank you for your reply. You're right, VS Code activates the extension when the "Open launch.json" command is executed:

``` text
...
[2019-05-23 08:17:14.848] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.csharp {"startup":false,"activationEvent":"onDebugInitialConfigurations"}
...
```

That's still unfortunate, though. I hope the feature you mentioned can help solving this. This blocked me for like 10 minutes. On a plane or train network this would be even worse.

**Comment by dancojocaru2000** [comment]
This is extremely unfortunate for the reason mentioned above. It sounds like bad design to start downloading dependencies once the extension is activated as well, instead of displaying one of those popup notifications in the bottom right asking if the user would like to do so.

**Comment by dancojocaru2000** [comment]
Aaaaand it happened again.

Waiting for 2 minutes (and counting) to debug a **Python** script really feels unacceptable.

**Comment by kwikwag** [comment]
This is a blocking feature for me and will cause an uninstall of the extension. Together with https://github.com/OmniSharp/omnisharp-vscode/issues/3862 this is extremely annoying. There should be no blocking network communication in performing an action in VS code because of an extension. One can run this in the background the have `launch.json` include C# templates only when completed (together with a notification that this is happening).
