### ISSUE TITLE
Provide project selector to pick startup project

### ISSUE THREAD

**Issue by DustinCampbell** [OmniSharp/omnisharp-vscode#310]
Picking a new startup project, should modify the launch.json so that F5 launches the project output under the debugger.

**Comment by gregg-miskelly** [comment]
Here is an idea -- instead of asking the user which project they want as the startup project (or maybe in addition to asking), maybe we should generate a different entry in launch.json and tasks.json for each launchable project. That way the user can easily switch around the startup project using the drop down built into VS Code.

**Comment by gregg-miskelly** [comment]
Here is how I decided to make this work --
1. When we generate launch.json, if there are multiple startup projects, the user will now get asked which one they want to launch.
2. If a user decides to make a different decision later, they can always rerun the '.NET: Generate Assets for Build and Debug' command.
