### ISSUE TITLE
Need dependencies offline download VSIX

### ISSUE THREAD

**Issue by xCyborg** [OmniSharp/omnisharp-vscode#3132]
Unlike the C++ plugin which offers full plugin offline support via VSIX, this plugin needs mandatory internet connection for dependency download.
Fix this please.

**Comment by akshita31** [comment]
@xCyborg We have support so that you can create vsix on a computer with internet and once created you can use it on a computer without internet. Please follow the instructions here https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-the-C%23-extension-to-a-computer-without-internet-connectivity#installing-on-a-computer-that-cannot-connect-to-the-internet to do so

**Comment by rchande** [comment]
@xCyborg We haven't heard back from you, so I'm going to close this.

**Comment by xCyborg** [comment]
@akshita31 It's too much hassle to implement especially on Windows, can't you just package the VSIX for each major version and make it available for download, please?
