### ISSUE TITLE
.NET Debugging is supported only in Microsoft versions of VS Code error

### ISSUE THREAD

**Issue by drk-mtr** [OmniSharp/omnisharp-vscode#3155]
## Update

Works fine in VSCode normal as opposed to Insiders so please feel free to close.

## Original

I receive an error ".NET Debugging is supported only in Microsoft versions of VS Code. See https://aka.ms/VSCode-DotNet-DbgLicense for more information." on what I believe is a copy of VSCode downloaded from Microsoft. Latest VSCode Insiders 1.37.0-insider. This worked previously.

## Steps to reproduce

- Create F# console app (netcoreapp3.0)
- Use default Launch.json and Tasks.json config to run app
- Receive debug error

## Expected  behavior

- Debugging works on MS version

## Actual behavior

Receive message to say `.NET Debugging is supported only in Microsoft versions of VS Code. See https://aka.ms/VSCode-DotNet-DbgLicense for more information.`

**Comment by drk-mtr** [comment]
Update: works fine in VSCode normal as opposed to Insiders so please feel free to close.

**Comment by gregg-miskelly** [comment]
@drk-mtr what OS are you on? Debugging normally works in Insiders, so I want to make sure the VS Code team didn't introduce a bug.

**Comment by drk-mtr** [comment]
Cheers for taking a look - I was actually just updating to close it:

Windows 10 Pro 1903 (build 10.0.18362.175)

**Comment by drk-mtr** [comment]
Just tried to re-create on:
VSCode 1.36.0 (succeeds)
VSCode 1.36.0-insider (succeeds)
VSCode 1.37.0-insider (fails)

The 1.36.0-insider is on a different PC that can't see any available updates, so I don't think I'm able to test on there without wiping and re-installing to get the latest. Guess they're staggering the releases.

**Comment by omartin2010** [comment]
seeing the same issue here.

**Comment by guardrex** [comment]
Same issue just cropped up for me. It wasn't doing this yesterday (before it updated iteself). I'm on ...

<img width="288" alt="Capture" src="https://user-images.githubusercontent.com/1622880/60736816-f385a200-9f1d-11e9-8498-30082410b750.PNG">

Win10 ... and I can't use/don't want the Insiders Version.

**Comment by gregg-miskelly** [comment]
@drk-mtr I *think* the VS Code team fixed the insiders problem in the latest build, at least I can't reproduce it, and omartin2010 indicated that the newest build fixes it for him. If you have the cycles, can you try updating to the latest and see if it works.

@guardrex I *think* your issue is different since it is happening in the release channel. It happens every time? Does it by chance go away if you uninstall+reinstall VS Code? If uninstall+reinstall doesn't fix it, would you mind opening a new issue.

**Comment by guardrex** [comment]
@gregg-miskelly Thanks ... I'll try an uninstall/reinstall on Saturday and open a new issue if it's still failing after that.

**Comment by guardrex** [comment]
I decided to wait a bit and see if anyone else hits this (or until a new VSC releases).

AFAICT, this is a regression on the update because it was working perfectly until immediately after the last update. Now, I get this error every debug attempt. In the meantime, I'll just `dotnet run` my apps without debugging.

**Comment by sborkowski** [comment]
@guardrex I'm having the exact same issue. Updated, and now I can no longer debug.

**Comment by drk-mtr** [comment]
I can confirm this appears to be resolved on vscode-insiders with commit versions starting `d50852` and `9296aa`. Thanks!

**Comment by gregg-miskelly** [comment]
@sborkowski @guardrex I decided to fork this bug between the insiders problem that this bug was originally opened about, and the problem that you two are running into that is affecting the release channel of VS Code. The new issue: https://github.com/OmniSharp/omnisharp-vscode/issues/3161
