### ISSUE TITLE
Selection prompt to extract method not worked in VSCode

### ISSUE THREAD

**Issue by lishali12345** [OmniSharp/omnisharp-vscode#317]
- VSCode Version:Version 1.1.0 (1.1.0)
- OS Version: Mac OS X EI Capitan

Steps to Reproduce:
1. Selection some lines code inside a method, will not show the prompt which will contains two menu item, just like "Extract Method" and "Use explicit type", which can be found in the release notes of v0.7.0
2. I just can not do this, and I google a lot for this, then I got nothing, so I'm here.

**Comment by DustinCampbell** [comment]
Hi -- thanks very much for taking the time to file this. We have some work to clean up the light bulb in VS code for C# and make it functional.

**Comment by DustinCampbell** [comment]
Hi @lishali12345: I haven't seen any problems with this in quite some time. There are a lot of fixes for Code Actions in the 1.7 release (due any day now). So, I'm going to go ahead and close. Please let me know if you have any more trouble.

**Comment by CanisLupus** [comment]
Hi @DustinCampbell, I don't know if I should be contacting you or the VSCode team, but the extract method feature doesn't work well in VSCode, though it is a bit hidden and I didn't even know it was there, even though I read this issue way back then. :)

Right now, running VSCode v1.9.1, I get a light bulb containing "extract method" to the left of a selected line or lines, but only if my selection is particular. I believe it is using the cursor position only and not what I have selected. Is this correct?

It's a bit hard to work with it if it doesn't follow the selection. For example, if I want to extract the contents of an "else", I don't seem to be able to, unless it's a single statement. On the other hand, if I extract with the cursor on the "else" word, it will extract the full if-else (I guess this is expected... maybe ;)).

Furthermore, running extract method seems to disregard my preference of tabs vs spaces, always using spaces, and will also change the formatting of the extracted code (though maybe it runs format and this is expected behavior).

If you'd like, I could submit this as a new issue. Thanks for reading!

**Comment by DustinCampbell** [comment]
Hi @CanisLupus: This is definitely an issue for us. The VS Code version doesn't matter much though. Rather, it's the version of C# for VS Code that's important. Feel free to file a new issue.

**Comment by CanisLupus** [comment]
I've updated the C# plugin to v1.7.0 before commenting, to see if it had fixed something in this regard, but it looks the same. I'll create a new issue and mention that. Thanks.

**Comment by michaelaye** [comment]
Still an issue for me on macOS 10.12.6, simply in the Interactive Playground even, not any fringe or self-installed programming language.
