### ISSUE TITLE
Provide Offline Packages with Release

### ISSUE THREAD

**Issue by jose-pr** [OmniSharp/omnisharp-vscode#3431]
## Environment data
any vs code

## Steps to reproduce
obtain vsix and install on computer with no internet

## Expected  behavior
Option to download precompiled vsix for your platform

## Actual behavior
Manual compilation.

Would like to request that precompiled/packaged of the extensions be made for the different platforms and made part of the github release like the [CPP](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools) extension does. Reason being that on closed/restricted network it is much easier and lest complicated if no compilation/ additional download are needed to build an offline package and the person that get tasked with the transfer may not be capable of the task either.

**Comment by gregg-miskelly** [comment]
We are currently waiting on the VS Code to support platform-specific exceptions (see https://github.com/microsoft/vscode/issues/23251). When that feature is delivered, we should be able to redo how this extension is delivered so that no further downloads are needed.

In the mean time, in case you haven't seen them, here are the 'offline instructions': https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-the-C%23-extension-to-a-computer-without-internet-connectivity

**Comment by Gigas002** [comment]
I've created a [repo](https://github.com/Gigas002/omnisharp-vscode-offline/releases), where I'll post offline versions of package installers. Hope this will help someone!
