### ISSUE TITLE
omnisharp.json doesn't work

### ISSUE THREAD

**Issue by Sergeyxow** [OmniSharp/omnisharp-vscode#3500]
My FormattingOptions doesn't work at all. I put omnisharp.json in project folder, it didn't work.  I put it in %USERDATA%/.omnisharp , it didn't work (file wasn't there actually, I created new one).

**Comment by filipw** [comment]
please provide a project that reproduces the issue - thanks

**Comment by Sergeyxow** [comment]
@filipw It's basically every project. I've tested this in folder just with two files (.cs and .json) and I've tested this in big project folders, no difference.

**Comment by filipw** [comment]
yeah I understand, but we need something to work with to troubleshoot your issue.

There is a whole issue template when creating a new issue - to post C# extension log, OmniSharp log, repro steps and other information - which you have all deleted and skipped.

Can you please provide all this info (especially OmniSharp log), the contents of your omnisharp.json file and the steps you are following - the expected result and the actual result. Otherwise it's really impossible to go any further with this. Thanks a lot.

**Comment by Sergeyxow** [comment]
@filipw I was thinking that formatting works automaticly like in Visual Studio, but then I added `"editor.formatOnSave": true` in setting.json and it's working. Sorry to bother you.

**Comment by filipw** [comment]
ah very good 😅

**Comment by WellspringCS** [comment]
I was having the same problem. Added that line...
```
`"editor.formatOnSave": true
```
and it appears that formatting is working now. Fingers crossed it will continue to do so! Thank you @Sergeyxow for the good tip, and @filipw for an awesome tool.

I'm writing this note, however, out of puzzlement. It works now when (Linux) I hit Ctrl+Shift+I -- which I did not associate with saving. I Assumed this set of keystrokes formats the whole file...without regard to saving or not saving. Why is this setting (formatOnSave) required for the document to format when I do Ctrl+Shift+I ??
