### ISSUE TITLE
Formatter doesn't respect editor.trimAutoWhitespace setting.

### ISSUE THREAD

**Issue by tobiasweger** [OmniSharp/omnisharp-vscode#3585]
When I format my document, the formatter removes whitespaces on empty lines even when I set `"editor.trimAutoWhitespace": false` in the settings of VS Code. 

**Before**
![Unbenannt](https://user-images.githubusercontent.com/19396049/74857881-a89d8b00-5344-11ea-8ed8-c128d366b5f7.PNG)

**After**
![Unbenannt2](https://user-images.githubusercontent.com/19396049/74858069-f6b28e80-5344-11ea-971f-57b2ef0bd06a.PNG)

 This behaviour is very annoying when you want to write some code e.g. inside the function and you have to hit the indentation button.
Please make the code of the formatter respect the `editor.trimAutoWhitespace` setting of VS Code

**Comment by JoeRobich** [comment]
@tobiasweger Sorry this is causing you issues. The Roslyn formatter always trims insignificant trailing whitespace (https://github.com/dotnet/roslyn/issues/41666). This is usually not a problem because VS and VS for Mac support "Virtual Space" and when clicking on the row the proper indentation is provided even though the spaces do not exist. There is an open issue for VS  Code to offer this same capability (https://github.com/microsoft/vscode/issues/13960); please vote it up to show it is important to you.

**Comment by cartermp** [comment]
Thanks for reporting. The behavior in Roslyn is by design as @JoeRobich mentioned, but because VSCode does not implement Virtual Space like Visual Studio (https://github.com/microsoft/vscode/issues/13960), the behavior you're seeing is happening.

**Comment by ivan-prodanov** [comment]
It doesn't look like VS code will implement virtual spaces anytime soon. The issue is 4 years old and there's no comment from the team. Could you guys just add an option in the OptionSet passed to the formatter to disable this?

**Comment by CyrusNajmabadi** [comment]
>  The issue is 4 years old and there's no comment from the team.

From our perspective the formatter is working as intended.

> Could you guys just add an option in the OptionSet passed to the formatter to disable this?

The formatting engine is already extremely complex, and we are very hesitant about making any sorts of changes to it.
