### ISSUE TITLE
Does it work with the latest .NET framework?

### ISSUE THREAD

**Issue by marcospgp** [OmniSharp/omnisharp-vscode#3639]
I kept getting the error `Error: The reference assemblies for .NETFramework,Version=v4.7.1 were not found` even though .NET framework 4.8 was installed. I tried installing version 4.7.1 and the error stopped being logged.

Does omnisharp not work with the latest version of the .NET framework?

Edit: Could this be an issue with Unity specifying the wrong .net framework version in the project settings?

**Comment by JoeRobich** [comment]
Hi @marcospgp, Most likely you are running against the minimal MSBuild that the C# extension ships with. To keep it small we do not include all the pieces of a full install, such as reference assemblies. For work loads that require more than we ship, we recommend installing [Build Tools for Visual Studio](https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2019) on windows or the stable release of [Mono on MacOS or Linux](https://www.mono-project.com/download/stable/).

**Comment by marcospgp** [comment]
@JoeRobich I'm not sure I understand. The error was related to the extension not being able to find a specific version of the .net framework, when a more recent version was installed. Installing the specific version that omnisharp was looking for solved the problem.

The question is why wasn't omnisharp detecting the latest version and requiring specifically the older version. Was it specified somewhere in the unity project config? Is it a default?

**Comment by JoeRobich** [comment]
Hi @marcospgp, When targeting a .NET Framework other than what is installed the compiler needs to know the shape of the APIs being referenced. The SDKs available in the Build Tools and Mono installers include reference assemblies that are functionally empty but contain the shape of the APIs. These reference assemblies are needed because the shape of the APIs change through the different versions of the Framework. This allows the compiler to compile against older versions of the .NET Framework than what is installed. You can read more about it here - https://github.com/dotnet/standard/blob/master/docs/history/evolution-of-design-time-assemblies.md#using-reference-assemblies

**Comment by cartermp** [comment]
Thanks for the report. This is something we'll have to consider by design/external, since supporting this scenario would mean pulling in reference assemblies and targeting packs for all .NET Framework versions with the extension. Since we don't want to bloat the extension to a large size, we'll require that targeting a different .NET Framework than what is on your machine will require installing those tools.

**Comment by marcospgp** [comment]
> we'll require that targeting a different .NET Framework than what is on your machine will require installing those tools.

I'm not sure I understand, in this case the extension was targeting a .net version different than the one on my machine - and I had to install the version it was looking for in order to make it work 🙂

**Comment by cartermp** [comment]
Yes, your experience here is considered by design. Unlike Visual Studio, the C# extension for VSCode doesn't carry .NET Framework setup dependencies for the various .NET Framework versions that have shipped over the years. We assume that you have them installed on your machine if you wish to target a particular version.

**Comment by marcospgp** [comment]
So it wasn't the extension that was trying to target the older version, it was me somehow? Maybe unity was seeiyng the target in some project configuration file?

**Comment by cartermp** [comment]
That is most likely the case, yes. The C# extension itself does not require .NET Framework 4.7.1 or higher. Usually this isn't a problem if you're using Visual Studio, since it also bundles the targeting packs (along with many other tools, making it a large installation). But since VSCode doesn't include all of that as a part of it's setup, issues like this can be hit from time to time when targeting .NET Framework.
