### ISSUE TITLE
Creating ".omnisharp" in user profile when vscode in portable mode

### ISSUE THREAD

**Issue by RichardRobertson** [OmniSharp/omnisharp-vscode#3684]
## Issue Description ##
Omnisharp plugin is creating an empty folder named ".omnisharp" in my local user profile even though vscode is configured to run in portable mode off a USB drive.

## Steps to Reproduce ##
Download zip version of vscode and extract it
Create "data" folder in same directory as "code.exe"
Interact with the Omnisharp plugin (anything including opening a workspace that uses it)
 
## Expected Behavior ##
All vscode data stored in portable "data" folder
 
## Actual Behavior ##
Omnisharp continues to create a ".omnisharp" folder in my local user profile.

## Environment information ##
**VSCode version**: 1.43.1
**C# Extension**: 1.21.14
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
Version: 3.1.102
Commit: 573d158fea
 
Runtime Environment:
OS Name: Windows
OS Version: 10.0.18363
OS Platform: Windows
RID: win10-x64
Base Path: C:\Users\rrobertson\AppData\Local\Microsoft\dotnet\sdk\3.1.102\
 
Host (useful for support):
Version: 3.1.2
Commit: 916b5cba26
 
.NET Core SDKs installed:
3.0.100 [C:\Users\rrobertson\AppData\Local\Microsoft\dotnet\sdk]
3.1.102 [C:\Users\rrobertson\AppData\Local\Microsoft\dotnet\sdk]
 
.NET Core runtimes installed:
Microsoft.AspNetCore.App 3.0.0 [C:\Users\rrobertson\AppData\Local\Microsoft\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.2 [C:\Users\rrobertson\AppData\Local\Microsoft\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 3.0.0 [C:\Users\rrobertson\AppData\Local\Microsoft\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.2 [C:\Users\rrobertson\AppData\Local\Microsoft\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 3.0.0 [C:\Users\rrobertson\AppData\Local\Microsoft\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 3.1.2 [C:\Users\rrobertson\AppData\Local\Microsoft\dotnet\shared\Microsoft.WindowsDesktop.App]
 
To install additional .NET Core runtimes or SDKs:
https://aka.ms/dotnet-download
</details>

<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.21.14|
|docomment|k--kato|0.1.8|
|vscode-nuget-package-manager|jmrog|1.1.6|
|vscode-todo-highlight|wayou|1.0.4|;

</details>

**Comment by filipw** [comment]
This folder is not created by the VS Code extension but by OmniSharp language server.
So what you are really asking for is some sort of a "portable" mode for the language server component (which it currently doesn't have). 
This behavior though really by design, as it uses it for global configuration (and for global configuration only). 
It's used not just for VS Code but shared by all other extensions for all editors.

If you run Omnisharp extension for VIM or for Emacs, it would create the same folder at the exact same location (unless it was already there).
You can change the location of that folder by setting environment variable `OMNISHARPHOME` with a relevant path.

> All vscode data stored in portable "data" folder

This would make no sense in this case, because as mentioned the goal of that folder is to share settings beyond VS Code and with other editors.

**Comment by RichardRobertson** [comment]
Well I guess the bug can be closed on this repo but I guess I'll "fix" it by running code.exe via batch file with that environment variable set so I can move that folder to my USB drive.
