### ISSUE TITLE
Question: license clarification

### ISSUE THREAD

**Issue by fbouteruche** [OmniSharp/omnisharp-vscode#3752]
Hi, 

It seems that the C# extension is licensed under a Microsoft license whereas the source code is licensed under a MIT license.

Could you please provide clarification?

Thanks.

**Comment by JoeRobich** [comment]
Hi @fbouteruche,

The short answer is that the extension is published under the Microsoft license because it may incorporate other assets that are not included in this repo and not licensed under MIT. This is similar to other projects/products such as VS Code and Chrome for example. 

Please let me know if there is a different question or concern that you would like addressed.

-Joey

**Comment by fbouteruche** [comment]
Have you already considered to have a version of the extension that uses netcoredbg to be able to release it under the MIT license? Thus, the extension would be usable inside Theia: https://github.com/eclipse-theia/theia. Right now, we can't use it inside Theia because of the license and vsdbg.

**Comment by cartermp** [comment]
@fbouteruche Yes, this has been considered, but ultimately a business decision was made that the .NET Core debugger (which is proprietary software from Microsoft) would only be available in Microsoft editors like VS, VSCode, and VS for Mac. If this changes, the license for use would adjust accordingly.

In the meantime, I believe the recommended extension for use within Theia is https://github.com/theia-ide/theia-csharp-extension
