### ISSUE TITLE
Clicking "Create a launch.json file" in VS Code triggers SDK downloads for non-C# projects

### ISSUE THREAD

**Issue by DanTup** [OmniSharp/omnisharp-vscode#4014]
I had a Flutter project open and clicked "Create a launch.json file" in the Run sidebar. This activated the C# extension which then started downloading SDKs.

<img width="1265" alt="Screenshot 2020-08-24 at 14 13 21" src="https://user-images.githubusercontent.com/1078012/91048794-16887f00-e614-11ea-9c2c-6c613127a456.png">

This happens quite frequently (I usually disable the extension because it annoys me, as I very rarely do C#). I think there should be something t prevent SDK components being downloaded for unrelated projects.

**Comment by gregg-miskelly** [comment]
@DanTup Unfortunately with the current design of extension deployment in VS Code, there is no good way to avoid this. Hopefully some day we will have https://github.com/microsoft/vscode/issues/23251 and the issue will get fixed.

**Comment by DanTup** [comment]
@gregg-miskelly out of interest - how will the issue linked above resolve this?

**Comment by gregg-miskelly** [comment]
It will not entirely resolve the problem - we still have work in this extension to take advantage of the new feature.

The problem you are complaining about is that this extension cannot fully install itself during extension install: this extension is a tiny amount of type script wrapping a bunch of C# and C++ code. We cannot include all that platform-specific code in our .vsix currently, so on first use we need to finish installing. Once there are platform-specific .vsix's we will not need to download anything on first use because VS Code would have downloaded everything during extension install/upgrade.

**Comment by DanTup** [comment]
@gregg-miskelly this doesn't seem like just a first use, I see it frequently (and I'm not uninstalling/reinstalling the extension). I assumed the SDK was being updated or something. Is that not the case? Should it only happen once? If so, are there any logs or anything I can capture when I next see it?

**Comment by gregg-miskelly** [comment]
It only happens after the extension is installed/upgraded, assuming that everything was successfully downloaded. There have been a few critical bugs lately, so the extension has shipped more updates than we normally do, which is probably why you noticed...

**Comment by DanTup** [comment]
> so the extension has shipped more updates than we normally do

Ah, that makes sense - I'd somewhat forgotten about updates given they're done quietly by VS Code and I don't see them so much. Thanks for the explanation!
