### ISSUE TITLE
Error in autocompletion with strings starting with an uppercase letter

### ISSUE THREAD

**Issue by ssoher** [OmniSharp/omnisharp-vscode#4063]
Issue Type: <b>Bug</b>

When overriding a protected void method named OnEnable, if I autocomplete with tab or return, the resulting code is as such:

`protected override voidnEnable() {
    basOnEnable();
}`

If I autocomplete "onEnable" (first o is lower case), the result is correct. This happens with any string that starts with an uppercase letter. I've tried "Awake", "OnDisable" etc.

![vsbug](https://user-images.githubusercontent.com/4283979/93018877-d5b0d400-f5db-11ea-99fb-c5b1cf0cbb00.gif)

Extension version: 1.23.2
VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
OS version: Windows_NT x64 10.0.18362

**Comment by nohwnd** [comment]
Looking into this.

**Comment by nohwnd** [comment]
This is because the completion does not handle correctly the case when completion keeps a bit of the original text. It works with `one`, because the typed text is on the given position 34, 45 (line, col) the returned change would be `OnEnabled()\n ...` with position 34, 45. But with `One` the change is `Enabled()\n ...` on position 34,47. 

This will skip this condition and instead use the one the is more complicated, that allows overwriting the existing code, but that path does not support this case correctly. 

https://github.com/OmniSharp/omnisharp-roslyn/blob/0587b50d9baea974a76adbbe063a1572ae9382aa/src/OmniSharp.Roslyn.CSharp/Services/Completion/CompletionService.cs#L239-L243

I was able to naively fix it by just taking the start of the typedText and prepending it to the proposed change. But this seems like oversimplifying the problem. 

https://github.com/OmniSharp/omnisharp-roslyn/pull/1941
