### ISSUE TITLE
OmniSharp server is not running

### ISSUE THREAD

**Issue by abusalaa7** [OmniSharp/omnisharp-vscode#41]
I see that issue already closed. Issue #17 but I'm still encountering this issue. I'm running osx 10.10.5 and vscode 0.10.9
![screen shot 2016-02-23 at 8 53 22 pm](https://cloud.githubusercontent.com/assets/8455022/13273206/c6b1b866-da6f-11e5-91c6-5121d5aecf41.png)

![screen shot 2016-02-23 at 8 55 43 pm](https://cloud.githubusercontent.com/assets/8455022/13273233/feaa42c4-da6f-11e5-9b86-59bbfc834c0a.png)

**Comment by johnvpetersen** [comment]
I resolved this by uninstalling the Core CLR runtmes and then reinstalling **without the global option** It appears the Omnisharp plugin for VS Code doesn't recognize global installs.  The same was true for the Omnisharp Atom plugin. That's how I discovered the issue - because the Atom plugin specifically stated where it was looking for the runtime. 

JP

**Comment by abusalaa7** [comment]
Can you provide steps on how to do that?

**Comment by johnvpetersen** [comment]
dnvm uninstall 1.0.0-rc1-update1 -r coreclr -arch x64
dnvm uninstall 1.0.0-rc1-update1 -r mono

Then, reinstall them - without the -g option.

**Comment by abusalaa7** [comment]
Unfortunately, that didn't work.

**Comment by DustinCampbell** [comment]
Hi, I'm sorry this issue got so stale. Now that DNX, DNVM and the like are long gone and .NET Core is here to stay, I'm going to go ahead and close this issue. Please let me know if this is still a problem for you.
