### ISSUE TITLE
Formatter breaks on non closed tags

### ISSUE THREAD

**Issue by m1212e** [OmniSharp/omnisharp-vscode#4284]
## Steps to reproduce
Use a <textarea /> tag in a Blazor project (.razor file) and enable the auto formatter.

## Expected  behavior
To format properly.

## Actual behavior
The auto formatter breaks and starts to indet some lines every time the file is formatted.

This is because of the tag syntax. If I use the full <textarea></textarea> version it works totally fine.

**Comment by JoeRobich** [comment]
cc: @ajaybhargavb

**Comment by ajaybhargavb** [comment]
@m1212e, thanks for reporting this. Razor internally uses VSCode's builtin HTML formatter to format the HTML parts of the document. Turns out this is the behavior of the HTML formatter. I was able to confirm this in a plain .html document in VSCode,
![image](https://user-images.githubusercontent.com/1579269/101692903-b8967080-3a25-11eb-95d1-c47034261527.png)

I suspect this is by design but you may want to file an issue in vscode directly to confirm if that is the case.

**Comment by m1212e** [comment]
Oh really? Never noticed it in plain html. But thanks, I'll do that

**Comment by m1212e** [comment]
They [answered](https://github.com/microsoft/vscode/issues/112182), would you take a look at it?
