### ISSUE TITLE
why it still cannot debug attach to x32 process

### ISSUE THREAD

**Issue by rdscfh** [OmniSharp/omnisharp-vscode#4546]
-------------------------------------------------------------------
You may only use the Microsoft .NET Core Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.
-------------------------------------------------------------------
无法启动调试。未能附加到进程: 仅可调试 64 位进程。

**Comment by gregg-miskelly** [comment]
Hi @rdscfh , I am assuming you are on Windows? 

If so: this isn't a supported scenario for the VS Code .NET debugger. 

If you don't care what bitness the process you are trying to debug runs under you could configure it to be a 64-bit process instead so that the VS Code debugger will work. You could also use full Visual Studio instead of VS Code as full Visual Studio supports this scenario.
