### ISSUE TITLE
Color and folding problems when inserting XML document text with "///"

### ISSUE THREAD

**Issue by FateArth** [OmniSharp/omnisharp-vscode#4761]
1、The color of XML such as 'summary' changes to a comment’s color
2、XML documents can be folded

# vscode
![QQ截图20210911160406](https://user-images.githubusercontent.com/70887549/132941101-9c291561-ac33-4f4a-932b-b7e7c3aa5923.png)

# VS
![QQ截图20210911160432](https://user-images.githubusercontent.com/70887549/132941116-c72616d0-0d2a-4e3e-a21a-0253e6bacb72.png)
# vs-folded
![QQ截图20210911160438](https://user-images.githubusercontent.com/70887549/132941182-0e69113c-a943-4ac4-903a-0cf4be078d33.png)

*Then I can enjoy using vscode*

**Comment by JoeRobich** [comment]
@FateArth Documentation Comments are foldable in VS Code. VS Code shows the folding controls when hovering over the margin. You can change this in settings so that they are always visible.
![image](https://user-images.githubusercontent.com/611219/132955857-0f46bb8b-7983-4aa0-bb1f-340b405b2620.png)

The color is an acquired taste. I recommend setting `csharp.semanticHighlighting.enabled` to `true` in settings and using the included Visual Studio 2019 Dark theme. It won't make the comments all green, but you can then edit the token colors to match your liking.

Before changing semantic token colors:
- Expanded:
![image](https://user-images.githubusercontent.com/611219/132955939-f76ae0a1-efb6-4663-adfb-3045d141eae7.png)

- Collapsed:
![image](https://user-images.githubusercontent.com/611219/132955959-67f27cca-4360-450d-87d1-52eecfd6e471.png)

Add the following section to your settings to make doc comments green.
```json
"editor.semanticTokenColorCustomizations": {
        "[Visual Studio 2019 Dark]": {
            "enabled": true,
            "rules": {
                "xmlDocCommentAttributeName": "#6A9955",
                "xmlDocCommentAttributeQuotes": "#6A9955",
                "xmlDocCommentAttributeValue": "#6A9955",
                "xmlDocCommentCDataSection": "#6A9955",
                "xmlDocCommentComment": "#6A9955",
                "xmlDocCommentDelimiter": "#6A9955",
                "xmlDocCommentEntityReference": "#6A9955",
                "xmlDocCommentName": "#6A9955",
                "xmlDocCommentProcessingInstruction": "#6A9955",
                "xmlDocCommentText": "#6A9955"
            }
        }
    },
 ```

After changing semantic token colors:
- Expanded:
![image](https://user-images.githubusercontent.com/611219/132956229-0a9c5693-0be1-4271-9cd8-c3dc1f88e58f.png)

- Collapsed:
![image](https://user-images.githubusercontent.com/611219/132956206-9f750ab2-caf1-4d6e-b308-e903020454f8.png)

Happy programming!
-Joey

**Comment by FateArth** [comment]
thank you

**Comment by FateArth** [comment]
> @FateArth文档注释在 VS Code 中是可折叠的。当鼠标悬停在边距上时，VS Code 会显示折叠控件。您可以在设置中更改此设置，以便它们始终可见。
> ![图片](https://user-images.githubusercontent.com/611219/132955857-0f46bb8b-7983-4aa0-bb1f-340b405b2620.png)
> 
> 颜色是后天习得的味道。我建议设置`csharp.semanticHighlighting.enabled`以`true`在设置和使用附带的Visual Studio 2019深色主题。它不会使评论全为绿色，但您可以编辑标记颜色以匹配您的喜好。
> 
> 在更改语义标记颜色之前：
> 
> * 扩展：
>   ![图片](https://user-images.githubusercontent.com/611219/132955939-f76ae0a1-efb6-4663-adfb-3045d141eae7.png)
> * 折叠：
>   ![图片](https://user-images.githubusercontent.com/611219/132955959-67f27cca-4360-450d-87d1-52eecfd6e471.png)
> 
> 将以下部分添加到您的设置中，使文档注释变为绿色。
> 
> ```json
> “ editor.semanticTokenColorCustomizations ”：{
>          “ [的Visual Studio 2019暗] ”：{
>              “启用”：真实的，
>              “规则”：{
>                  “ xmlDocCommentAttributeName ”： “＃6A9955 ”，
>                  “ xmlDocCommentAttributeQuotes ”： “＃6A9955 ”，
>                  “ xmlDocCommentAttributeValue ”： ”#6A9955 "，
>                  “ xmlDocCommentCDataSection ”：“＃6A9955 ”，
>                  “ xmlDocCommentComment ”：“＃6A9955 ”，
>                  “ xmlDocCommentDelimiter ”：“＃6A9955 ”，
>                  “ xmlDocCommentEntityReference ”：“＃6A9955 ”，
>                  “ xmlDocCommentName ”：“＃6A9955 ”，
>                 ”xmlDocCommentProcessingInstruction " : " #6A9955 " ,
>                  " xmlDocCommentText " : " #6A9955 " 
>             } 
>         } 
>     },
> ```
> 
> 更改语义标记颜色后：
> 
> * 扩展：
>   ![图片](https://user-images.githubusercontent.com/611219/132956229-0a9c5693-0be1-4271-9cd8-c3dc1f88e58f.png)
> * 折叠：
>   ![图片](https://user-images.githubusercontent.com/611219/132956206-9f750ab2-caf1-4d6e-b308-e903020454f8.png)
> 
> 编程快乐！
> -乔伊

But can the description be displayed after the summary after folding

**Comment by JoeRobich** [comment]
Customizing the folded text is not currently supported by VS Code. There is an open feature request for adding that functionality https://github.com/microsoft/vscode/issues/70794. You should vote it up to show your support for the feature.
