### ISSUE TITLE
Changelog still shows 1.23.16 as "Not released yet"

### ISSUE THREAD

**Issue by gregvanl** [OmniSharp/omnisharp-vscode#4824]
This shows up in the VS Code Extensions view Changelog tab.

![image](https://user-images.githubusercontent.com/12818376/137373998-ceae9ba9-017b-4e51-a8a2-bb840e0ee99e.png)

**Comment by JoeRobich** [comment]
@gregvanl  Thanks for opening this issue. Unfortunately the changelog shown in the marketplace comes from the commit used to build the shipping package. Since we do not know how long validation will take, we do not update this bit of text until after release. It has already been updated in main - see https://github.com/OmniSharp/omnisharp-vscode/blob/master/CHANGELOG.md#12316-oct-12th-2021
