### ISSUE TITLE
Q: debugging Release builds

### ISSUE THREAD

**Issue by tmds** [OmniSharp/omnisharp-vscode#4897]
I tried attaching the debugger to a .NET app that was built in Release configuration.
I could not set any breakpoints.

Can I change the project settings so the Release configuration build becomes debuggable?
Or can breakpoints only work when using Debug configuration?

**Comment by gregg-miskelly** [comment]
As you have discovered, by default, code compiled for release configuration cannot be debugged. There are a couple of things you can do depending on what you are ultimately trying to accomplish:

1. Disable [`justMyCode`](https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger-launchjson.md#just-my-code) and optionally enable [`suppressJITOptimizations`](https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger-launchjson.md#suppress-jit-optimizations) -- if you want to debug the bits that are ultimately produced from your retail build, this is the way to go. Suppressing JIT Optimizations is optional, but debugging optimized code in .NET doesn't work very well - many breakpoints just cannot be set, stepping often will not work and variable inspection will mostly be busted. So unless you really need optimizations for some reasons I would recommend this approach.
2. Change project file options to disable compile-time optimizations -- if you suspect you have a retail-only bug caused by conditional compilation (`#if DEBUG` or Debug.Assert's with side effects) you can change the `Optimize` project file properties to make release configuration still produce debugable code. If you do this, there is no need to tweak debugger options.

**Comment by tmds** [comment]
Thank you, @gregg-miskelly.
