### ISSUE TITLE
Cannot install 1.24.0 version of the extension

### ISSUE THREAD

**Issue by Igorgro** [OmniSharp/omnisharp-vscode#5014]
I'm trying to install the newest version of the extension, but vscode still downloading version 1.23.17. I've unstalled the extension completely and reloaded vscode multiple time but it still downloads the older version.

Vscode version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:39:46.686Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.16.1-arch1-1

**Comment by jesperkristensen** [comment]
I have the same issue. I am using WSL. This page https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csharp shows Linux x64 supported for version 1.23.17 but only Linux ARM64 supported for version 1.24.0. When will the extension version 1.24.0 be released for Linux x64? The C# extension has been completely broken since the November 2021 update of VS Code (#4907), so I really want to upgrade to the fixed version as soon as possible.

**Comment by Igorgro** [comment]
Hmm, on the release page there is a x64 linux vsix available 
![image](https://user-images.githubusercontent.com/22894169/150491383-4dcb2a7b-c70c-489a-ba6a-e5a28e4d03c1.png)

**Comment by JoeRobich** [comment]
@Igorgro Thanks for logging this issue. Looks like we missed a package when pushing the new version out. I am pushing the x64 package now.

FYI @nohwnd

**Comment by JoeRobich** [comment]
@Igorgro Looks like it is up on the marketplace now. Closing this issue. Please reopen if you continue to have issues.
