### ISSUE TITLE
Debugger: reports bad bind information when binding to a line with no associated code.

### ISSUE THREAD

**Issue by GraceDong** [OmniSharp/omnisharp-vscode#512]
## Environment data

`dotnet --info` output:
VS Code version:
C# Extension version:
## Steps to reproduce

1 Set a breakpoint at a line of "using System.Linq;" in HomeController.cs
## Expected  behavior

This breakpoint cannot be set
## Actual behavior

The breakpoint can still be set, and I tried this in Visual Studio, that cannot be set in using statements. So is it by-design behavior?

**Comment by gregg-miskelly** [comment]
The fact that a breakpoint can be set on 'using System.Linq;' is by-design for VS Code.
The fact that the breakpoint binds though instead of showing an error is a bug. clrdbg should be reporting a warning breakpoint here but it is not. Maybe it is just binding to a different line, but if so we need to at least move the glyph to where the breakpoint bound.

    C setBreakpoints: {"source":{"name":"Program.cs","path":"d:\\proj\\clicon\\Program.cs","sourceReference":0},"lines":[1],"breakpoints":[{"line":1}]}
    1: (140691) <-1026-break-insert -f --SHA1checksum 5d54950e9a38b3d2a0db1c63f061d81daedbc147,1a378052312679f0e9826ff9ac195f5f1c988fc0 Program.cs:1
    1: (140707) ->1026^done,bkpt={number="5",type="breakpoint",disp="keep",enabled="y"}
    1: (140707) 1026: elapsed time 15
    1: (140707) ->(gdb)
     R: {"success":true,"message":null,"request_seq":13,"command":"setBreakpoints","body":{"breakpoints":[{"id":3,"verified":true,"line":1,"message":null}]},"running":false,"refs":null,"seq":0,"type":"response"}
    E breakpoint: {"reason":"change","breakpoint":{"id":3,"verified":true,"line":1,"message":null},"type":"breakpoint"}

**Comment by WardenGnaw** [comment]
This seems to be fixed with VsDbg.

Events:
-> (C) {"command":"setBreakpoints","arguments":{"source":{"path":"c:\\Users\\waan\\DummyProjects\\csharpaspnet\\Controllers\\HomeController.cs","checksums":[{"algorithm":"SHA1","checksum":"45fde0440abffa5022494c3aa858a4b3e52c32ab"},{"algorithm":"SHA256","checksum":"3cbd19e01afe66af3a23cab21c983c5facac910b1e324ef60d3b40d61c546a7c"},{"algorithm":"SHA1","checksum":"10ba5a9bdc0374b3556810dc66fb51b9533e41fe"},{"algorithm":"SHA256","checksum":"aed8f3525503a71140db3a5e80b356a6c98b084abfb35a28e47165a05117f2ec"}]},"lines":[3],"breakpoints":[{"line":3}],"sourceModified":false},"type":"request","seq":4}

<- (R) {"seq":6,"type":"response","request_seq":4,"success":true,"command":"setBreakpoints","message":"","body":{"breakpoints":[{"id":1,"verified":false,"message":"The breakpoint is pending and will be resolved when debugging starts.","line":3}]}}

<- (E) {"seq":12,"type":"event","event":"breakpoint","body":{"reason":"changed","breakpoint":{"id":1,"verified":false,"message":"No symbols have been loaded for this document.","line":3}}}

<- (E) {"seq":20,"type":"event","event":"breakpoint","body":{"reason":"changed","breakpoint":{"id":1,"verified":true,"source":{"name":"HomeController.cs","path":"c:\\Users\\waan\\DummyProjects\\csharpaspnet\\Controllers\\HomeController.cs","checksums":[]},"line":12,"endLine":12}}}

Inserting breakpoint on using:
![image](https://cloud.githubusercontent.com/assets/3953714/25200095/ff52bdfe-2501-11e7-9686-745556a8ea39.png)

After F5
![image](https://cloud.githubusercontent.com/assets/3953714/25200101/0bc66180-2502-11e7-84e1-f582cad4174e.png)
