### ISSUE TITLE
Debugger: VSCode regards all the warnings in the VS as errors

### ISSUE THREAD

**Issue by GraceDong** [OmniSharp/omnisharp-vscode#522]
## Environment data
`dotnet --info` output:
VS Code version:
C# Extension version:

## Steps to reproduce
1 Insert a line of "int a = 1;" in HomeController.cs
2 Press F5 to start debugging

## Expected  behavior
The project should be build successfully and have a warning in output window 

## Actual behavior
This project cannot be build successfully. I tried this issue in VS, this was treated as a warning. If so, seems that the warnings in VSCode takes no effect in compiling system.

**Comment by gregg-miskelly** [comment]
Just like in VS, warnings will not cause the build to fail by default. But you can still get to them. There is a little warning/error icon thing in the bottom left:

![warning-error-icons](https://cloud.githubusercontent.com/assets/11078489/16531915/adc5792c-3f83-11e6-8746-48e2f069604c.JPG)

Also just like VS, the warnings will not be seen if your project doesn't build because it is already up to date.
