### ISSUE TITLE
Why "Console.ReadLine()" works when typing "clear" and then typing "dotnet run" but doesn't work when typing "clear | dotnet run"?

### ISSUE THREAD

**Issue by LazieWouters** [OmniSharp/omnisharp-vscode#5310]
## Issue Description ##
 "Console.ReadLine()" works when typing "clear" and then typing "dotnet run" but doesn't work when typing "clear | dotnet run"
## Steps to Reproduce ##
The steps are in the attached video
### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.69.2
**C# Extension**: 1.25.0

<details><summary>Dotnet Information</summary>
SDK do .NET (refletindo qualquer global.json):
 Version:   6.0.301
 Commit:    43f9b18481

Ambiente de runtime:
 OS Name:     Windows
 OS Version:  10.0.22622
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.301\

Host (useful for support):
  Version: 6.0.6
  Commit:  7cca709db2

.NET SDKs installed:
  6.0.301 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|activitybar-separator|ctf0|0.0.1|
|csharp|ms-dotnettools|1.25.0|
|customize-toolbar|liangruliu|0.1.2|
|errorlens|usernamehw|3.5.2|
|jupyter|ms-toolsai|2022.6.1201981810|
|jupyter-keymap|ms-toolsai|1.0.0|
|jupyter-renderers|ms-toolsai|1.0.8|
|MagicPython|magicstack|1.1.0|
|msbuild-project-tools|tintoy|0.4.4|
|new-moon-vscode|taniarascia|1.8.8|
|python|ms-python|2022.10.1|
|rest-client|humao|0.25.0|
|terminal|formulahendry|0.0.10|
|vs-code-semicolon-insertion|chrisvltn|0.0.6|
|vscode-autohide|sirmspencer|1.0.7|
|vscode-pylance|ms-python|2022.7.30|
|vscodeintellicode|VisualStudioExptTeam|1.2.22|;

</details>

https://user-images.githubusercontent.com/77227512/179741356-9ecb826b-426e-40bb-9014-001bb11748d6.mp4

**Comment by JoeRobich** [comment]
Since this is not an issue with the C# extension itself, you question would be better answered by the dotnet/runtime repo. Follow this link to open an issue https://github.com/dotnet/runtime/issues/new/choose

Looking at your video though I can take a stab at helping. 

<img width="540" alt="image" src="https://user-images.githubusercontent.com/611219/179853608-fbb620f0-e0ae-4ece-ac80-d9182a5d4248.png">

The reported error is that you cannot invoke `Console.ReadKey` when input has been redirected (See [docs](https://docs.microsoft.com/en-us/dotnet/api/system.console.readkey?view=net-6.0)). Using pipes (such as `clear | dotnet run`) to launch programs in sequence does redirect the output from one to the input of the next. This causes the error that you are seeing. You can check whether the applications input has been redirected by testing the `Console.IsInputRedirected` property.
