### ISSUE TITLE
Make dotnet debug launch config independent of the framework version number

### ISSUE THREAD

**Issue by fpintos** [OmniSharp/omnisharp-vscode#5505]
## Is your feature request related to a problem? Please describe.
When we create a dotnet program with vscode, for example, following https://learn.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio-code, we end up with a launch.json file that has the framework version hardcoded. For example, it says:
"program": "${workspaceFolder}/bin/Debug/net7.0/myApp.dll",

If someone on the team updates the version of the framework that is used by the application and forgets to update the launch.json file, other developers end up with a broken F5-debug experience. This has happened in our project multiple times, as we moved from 3.0 to 5.0, then to 6.0 and now to 7.0.

## Describe the solution you would like
Make the setting in launch.json version independent by default.
The debug launcher could try to figure out the folder where the application was built, and launch from there by default.
For example, maybe the configuration should say something like:
“program”: “${debugOutput}/${assemblyName}.dll”

## Applicable Scenarios
Debugging dotnet applications in Visual Studio Code.

**Comment by gregg-miskelly** [comment]
I don't think we will do exactly what you are suggesting here, but we do have plans to hopefully move launch.json to specifying a project to launch rather than `program`, which would solve the issue you are getting at. There is a very old work item to track this (https://github.com/OmniSharp/omnisharp-vscode/issues/1876), but hopefully we aren't quite as far from working on this as the age of this work item might imply.
