### ISSUE TITLE
[Bug] Omnisharp shows false errors on winforms/WPF designer code

### ISSUE THREAD

**Issue by 06needhamt** [OmniSharp/omnisharp-vscode#63]
Whats the issue?

The issue is that omnisharp shows false errors in code that references winforms / WPF components which would be implemented in the designer code. i.e. any references to controls placed on UI windows are flagged up as errors

**Comment by DustinCampbell** [comment]
@06needhamt: Sorry for the delay here. I realize that this issue is *very* old. However, if you're still interested in getting this working, I'd like to help.

If you're willing to help, I have a few questions:

* What OS are you experiencing this with?
* What version of VS Code are you running?
* What version of the C# Extension for VS Code are you running?
* Do you have a project that you could share that demonstrates the problem?
* Could you provide your OmniSharp log from VS Code? To get this, open your project and then select View->Output and choose "OmniSharp Log" on the right side of the Output pane.

Thanks!

**Comment by 06needhamt** [comment]
I'm on vacation right now will take a look when i am home

**Comment by 06needhamt** [comment]
@DustinCampbell Sorry For the delay just got back from vacation today 
I am using Windows 10 Build 14393.51
With VS Code Version 1.4.0
And C# Extension Version 1.4.1 
See Attached Project and OmniSharp logs
[omnisharp-log.txt](https://github.com/OmniSharp/omnisharp-vscode/files/461425/omnisharp-log.txt)
[Sample Project](https://mega.nz/#!QswnFaoQ!aRVAhp46dEOkvLDE4Mv9tNWjepW0MqKabZLAJ0Y2e-U)
Hope this helps you solve this issue please let me know if you need any more information

**Comment by rchande** [comment]
@06needhamt This issue is now *extremely* old. I'm closing it, but feel free to file a new one if you're still having issues.
