### ISSUE TITLE
Failed to start OmniSharp

### ISSUE THREAD

**Issue by jrieken** [OmniSharp/omnisharp-vscode#655]
_From @mm75 on August 11, 2016 18:26_

- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:49:32.489Z)
- OS Version: Linux x64 4.2.0-42-generic

[INFO] Starting OmniSharp at '/home/jhondoe/www/hwapp'...
[INFO] Started OmniSharp from '/home/jhondoe/.vscode/extensions/ms-vscode.csharp-1.3.0/out/.omnisharp-coreclr/OmniSharp' with process id 15200...
Failed to initialize CoreCLR, HRESULT: 0x80131500
[ERROR] Error: Failed to start OmniSharp

_Copied from original issue: Microsoft/vscode#10442_

**Comment by DustinCampbell** [comment]
@mm75: what Linux distro are you running?

**Comment by mm75** [comment]
Plataform: Ubuntu 15.10 wily
Desktop: Mate

**Comment by DustinCampbell** [comment]
Ubuntu 15.10? OmniSharp should only install and run on 14 or 16. I'll install that distro and see why (https://github.com/OmniSharp/omnisharp-vscode/blob/master/src/platform.ts#L61-L69) is allowing 15.10.

**Comment by DustinCampbell** [comment]
Now that I step through the code, I see why it isn't working. It's a rookie mistake: case fall through. :smile: Since, the "ubuntu" case only checks for versions 14 or 16, version 15 is unhandled. However, there's no break statement, so it just falls through to the "centos" case.

Unfortunately, Ubuntu 15.10 is not a supported Linux distro today. You can get things working with the Mono version of OmniSharp by using the following steps though:

1. Install Mono
2. Download and untar the mono flavor of OmniSharp [here](https://github.com/OmniSharp/omnisharp-roslyn/releases).
3. In Visual Studio Code, select Preferences -> User Settings.
4. In settings.json, add the following:

```JSON
"csharp.omnisharp": "/path/to/the/OmniSharp/executable/you/just/untarred",
"csharp.omnisharpUsesMono": true
```

Note: In the next release of the C# Extension, we're changing these values to:

```JSON
"omnisharp.path": "/path/to/the/OmniSharp/executable/you/just/untarred",
"omnisharp.usesMono": true
```

**Comment by DustinCampbell** [comment]
Note: We intend to make the process of acquiring the mono version of OmniSharp easier on any Linux distro. #593

**Comment by mm75** [comment]
Thank you for your attention!!!

I will follow your suggestions

2016-08-25 12:18 GMT-03:00 Dustin Campbell <notifications@github.com>:

**Comment by DustinCampbell** [comment]
Excellent! Let me know how it goes.
