### ISSUE TITLE
Feature request: Better C# syntax colorizer

### ISSUE THREAD

**Issue by aeschli** [OmniSharp/omnisharp-vscode#674]
_From @nfantone on August 17, 2016 14:57_

On latest Insiders (`1.5.0-55168276e4c0b6ec2404ac20af04eeed5f5b1000`), C# syntax  highlighting look _very_ bland.

<img width="823" alt="screen shot 2016-08-17 at 11 39 26 am" src="https://cloud.githubusercontent.com/assets/476069/17740664/d36e14c0-646f-11e6-93a3-9523e0ca963f.png">

As you can see, almost 70% of the text is just plain white, with only a few keyword being blue. Tried different themes as well, and all of them colorize the same bits leaving what was white-ish in the default theme intact.

Am I doing something wrong? Is there an extension of sorts for enhancing this? I am new to C# in general, so perhaps this is to be expected? Or are there plans to support better syntax highlighting in the future?

_Copied from original issue: Microsoft/vscode#10619_

**Comment by johanneskopf** [comment]
Same here with the latest 1.5.0 insider.
"Vector3", "Input" and "Screen" for example in my picture should definitely be colorized.

![csharp_syntaxhighlighting](https://cloud.githubusercontent.com/assets/13490371/17749831/b0231b64-64bf-11e6-9b9e-0e15948accb5.PNG)

**Comment by aeschli** [comment]
@DustinCampbell You are correct, we only have syntax highlighting through text mate grammars. Some grammars go quite far as to also parse statements and expressions, but depending on the complexity of the language this is not feasible.

**Comment by cwe1ss** [comment]
@nfantone @aeschli seems like this specific screenshot is from using the "Dark" theme instead of "Dark+" (which has nicer highlighting), isn't it? 

Themes can be changed in the command palette by typing "Preferences: Color Theme"

**Comment by nfantone** [comment]
@cwe1ss While it's still has plenty of room for improvement,

 since `1.4.0` release, colorizer greatly improved. That screenshot was taken almost a month ago, now. Not entirely sure, but it should have been taken using `1.3.0`.

However, I do remember that switching themes at that moment did absolutely nothing but change the colors of what was _already colorized_ in the shown theme.

Currently, it looks something like this (using _Dark+_):

<img width="815" alt="screen shot 2016-09-09 at 2 56 44 pm" src="https://cloud.githubusercontent.com/assets/476069/18389387/aacfd14e-769d-11e6-8465-457d00f931fb.png">

It'd be great if classes whose static members are being accessed would be somewhat emphasized and not left completely white (like that `Random.Range` call). As an example, take a look at what [Visual Studio does](https://i.stack.imgur.com/4ERq0.png).

**Comment by ivanz** [comment]
Found this feature request in VSCode for exposing a way to plug-in programmatic (semantic) highlighting: https://github.com/Microsoft/vscode/issues/585

Until that's implemented we can only do syntax highlighting based on regular expressions, which can do only so much.

**Comment by DustinCampbell** [comment]
Thanks @ivanz. I went ahead and commented on that issue as well.

**Comment by nfantone** [comment]
@DustinCampbell One thing I can't quite get my head around is why we need semantic knowledge of an instruction to change the color of `Customer` in something like this: `Customer.Find()`. I know _next to nothing_ about textmate, but it sure seems like something incredibly simple to implement with a regex. 

The only complication I can think of is if someones uses _PascalCase_ to name their variables or does not with classes names. But, then again, those people _deserve_ not to have proper syntax highlighting.

If you assume some kind of coding standard, you can begin to cover a very wide range of cases without semantic shenanigans.

**Comment by DustinCampbell** [comment]
@nfantone: It's not shenanigans. Casing isn't enough to even make an educated guess. Without semantically knowing what `Customer` is, we have no why of knowing whether its a class, a property, a public field, etc.

Note that we actually already have *all* of this information with OmniSharp. We have all the same information that is used to colorize Visual Studio. We just need a way to present that information in VS Code.

**Comment by nfantone** [comment]
@DustinCampbell You are right. I know it's not "shenanigans". Bad wording, sorry. I disagree with this, tough:

> Casing isn't enough to even make an educated guess.

Frankly, I believe it's more than enough. It won't be an _exact match_, but it'll sure be educated.

My point was (is) why aren't we colorizing those terms anyway? Why is the alternative (mostly white text) preferable? Maybe I'm alone with this opinion here, but I'd take having `Customer` in `Customer.Find()` being of a different color than `Find()` any day - regardless of it being a static reference, a local variable or a class attribute. 

Just for reference, that is what the Javascript syntax highlighter in, say, ST3 does. See below.

<img width="773" alt="screen shot 2016-09-25 at 8 49 33 pm" src="https://cloud.githubusercontent.com/assets/476069/18817792/a8cea9b2-8361-11e6-9772-09a4974e3161.png">

Both `Object` and `Customer` are colorized different than their members.

**Comment by DustinCampbell** [comment]
We're definitely accepting pull requests. However, as we already have exactly the information to colorize, we're not willing to spend cycles adding heuristics to the reg-ex based grammar to make it look right some of the time.

JavaScript is not really a fair comparison as the standard for casing is pretty different. In C#, we'd get it wrong a *lot* more often.

**Comment by nfantone** [comment]
Ok, fair enough. Understood.

We'll just wait until there's a proper way to output the information you already have in the editor.

**Comment by kkukshtel** [comment]
Just want to comment on this issue as well and still state that it's a headache on VSCode. Not sure if anything has changed, but the highlighting available is poor at best across almost all themes.

@DustinCampbell - if you have any pointers about where to start to make this a community effor it woudl be much appreciated.

![highlight](https://cloud.githubusercontent.com/assets/7715279/21053901/6dcc847e-bdf9-11e6-85c7-7508fbe9b465.PNG)

**Comment by DustinCampbell** [comment]
@kkukshtel: The regular expressions used to colorize code are on this repo and we're definitely accepted pull requests. The problem (I think) is that you're looking for colorization that requires semantic information (i.e. is this identifier a class, an interface, a property, etc.?), which can't be determine via regular expressions. We already have all of that information with OmniSharp via Roslyn, but what is missing is an API to add it to VS Code. This issue is tracking a VS Code API that would allow us to take advantage of that information and provide better colorization (identical to Visual Studio) is here: https://github.com/Microsoft/vscode/issues/585. cc @chrisdias, @jrieken

**Comment by DustinCampbell** [comment]
This should all look much in the next release:

![image](https://cloud.githubusercontent.com/assets/116161/21823142/c1090f56-d72e-11e6-8fc4-3dbb3bf65d5e.png)

![image](https://cloud.githubusercontent.com/assets/116161/21823153/c8da1e50-d72e-11e6-82d9-b2f150113c02.png)

![image](https://cloud.githubusercontent.com/assets/116161/21823159/cb5515a4-d72e-11e6-8d9f-431ff4a8121e.png)

**Comment by kkukshtel** [comment]
😍😍😍😍😍😍😍😍
