### ISSUE TITLE
Debugger:Unable to resolve 'System.Reflection.Metadata' for '.NETCoreApp.Version=v1.0'

### ISSUE THREAD

**Issue by GraceDong** [OmniSharp/omnisharp-vscode#701]
## Environment data
`dotnet --info` output:
VS Code version: 1.4.0
C# Extension version: v.1.4.0-beta6
.NET Core version: 1.0.0-SDK Preview2

## Steps to reproduce
1. Create a simple .NET Core project use command.
2. Open VSCode to install the C# extension of 1.4.0-beta6 , restart VSCode to make the extension takes effect.
3. Load the existing hwapp folder I just created on VSCode. 
4.Press F5 to start debugging

## Expected  behavior
The project should be start debugging.

## Actual behavior
This project can't start debugging and show some error message in VSCode. Attached as below:
![error1](https://cloud.githubusercontent.com/assets/20184778/17921835/7fc07864-6a0e-11e6-87d4-546a27eceb15.png)
![error2](https://cloud.githubusercontent.com/assets/20184778/17921834/7fc03b06-6a0e-11e6-8dca-d2fc44289f20.PNG)
![output](https://cloud.githubusercontent.com/assets/20184778/17921836/7fc38e5a-6a0e-11e6-8ba1-3faf4763f4e9.PNG)

**Comment by gregg-miskelly** [comment]
@chuckries @caslan I think we should pull the latest beta release until this is resolved.

**Comment by DustinCampbell** [comment]
I got this as well.

**Comment by gregg-miskelly** [comment]
I am going to pull the release now.

**Comment by DustinCampbell** [comment]
OK. If you decide to completely delete the release, go ahead and [remove the tag](http://wptheming.com/2011/04/add-remove-github-tags/) as well.

**Comment by gregg-miskelly** [comment]
The GitHub documentation seems to say that it is possible to delete a release, but it isn't working for me (maybe because I didn't create it?). So I pulled the .vsix and I edited the description so that hopefully it is obvious that the release shouldn't be used. @chuckries do you want to see if you have access to delete it?

**Comment by DustinCampbell** [comment]
I can delete it.

**Comment by DustinCampbell** [comment]
Release is removed. Note: the trick is to delete the tag from GitHub, which converts the release to a "draft" release, which can be discarded.

**Comment by chuckries** [comment]
Sorry everybody, this is my fault. I added the additional nuget feed but didn't want to push the change since it is (hopefully) a temporary workaround. I built the extension locally that works. When I created the release, the CI system built the package for the release page and it did not have my NuGet.config change. I will fix this.

**Comment by chuckries** [comment]
This has been fixed, the System.Reflection.Metadata we need has been published to nuget.org, no workaround required.
