### ISSUE TITLE
Debugger:Debug console doesn't appear when set "internalConsoleOptions" value is "openOnFirstSessionStart" in lanuch.json file 

### ISSUE THREAD

**Issue by qian6** [OmniSharp/omnisharp-vscode#705]
## Environment data
`dotnet --info` output:
VS Code version:1.4.0
C# Extension version: v.1.4.0-beta6
.NET Core version: 1.0.0-SDK Preview2

## Steps to reproduce
1. Open hwapp folder in attachments directly  
2. Set a breankpoint at line of 9 in Program.cs file
3. Press F5 to start debugging
4. Update "internalConsoleOptions"  in launch.json as following:
    
        "internalConsoleOptions": "openOnFirstSessionStart"
5. Press F5 to start debugging
6. Observed Debug Console

## Expected  behavior
It should appear Debug Console

## Actual behavior
Debug Console doesn't appear 

##Investigation
When I use a new c# project, directly update "internalConsoleOptions": "openOnFirstSessionStart",start debugging and debug console will appear

[hwapp.zip](https://github.com/OmniSharp/omnisharp-vscode/files/434384/hwapp.zip)

**Comment by gregg-miskelly** [comment]
@qian6 this isn't a C# extension issue. It is either 'by design' or a VS Code issue. If you have really *never* F5'ed this folder before on this machine, then I would suggest reopening the issue at http://github.com/Microsoft/vscode/issues. If you have previously launched this project ever I believe this is 'by design'.
