### ISSUE TITLE
Unable to get IntelliSense for C# on a multi folder structure 

### ISSUE THREAD

**Issue by sandy081** [OmniSharp/omnisharp-vscode#713]
_From @afoliaco on August 25, 2016 2:56_

- VSCode Version: 1.4
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Create the following folder structure 
SampleCode/src/Project1
SampleCode/src/Project2
2. Run dotnet new and dotnet restore to create the applications  and the new application restore all the correct dependencies. 
3. Create sample class in Project2 and add the Project2 reference on  Projec1 project.json. 

Note: I create this repo for duplication https://github.com/afoliaco/InventoryServices, also you can see question on StackOverflow http://stackoverflow.com/questions/39124742/vscode-multiples-projects-reference

_Copied from original issue: Microsoft/vscode#10929_

**Comment by sandy081** [comment]
There is no multi project support in VS Code yet. But I think how to handle intelli-sense when multiple folders / projects are open is upto the extension.

**Comment by DustinCampbell** [comment]
Hi, this project is working for me OK. When first opened, there's a panel that reads, "Select project", at the bottom right corner of VS Code:

![image](https://cloud.githubusercontent.com/assets/116161/18026593/41f28f0a-6c01-11e6-8022-d2ab0fe57545.png)

Click "Select project" and a picker should be displayed allowing you to pick the project you're working on:

![image](https://cloud.githubusercontent.com/assets/116161/18026595/5d00962a-6c01-11e6-9611-8ec3e61e6ae7.png)

Since Project1 depends on Project2, I'd recommend choosing that one to get IntelliSense for both projects. After a few moments, OmniSharp should download and install, providing you with IntelliSense.

Let me know if this helps!
