### ISSUE TITLE
Auto generate triple slash comments with parameters

### ISSUE THREAD

**Issue by jrieken** [OmniSharp/omnisharp-vscode#8]
_From @EmYeuCoGiao on December 25, 2015 3:43_

I use VSCode for unity3d dev, i type /// but this not auto gennerate
<code>
///<summary>

///
///</summary>

///<param name=""></param>
</code>
![capture](https://cloud.githubusercontent.com/assets/14220005/11999614/a40d4bae-aaf4-11e5-96ce-064b8b02bb7e.PNG)

_Copied from original issue: Microsoft/vscode#1644_

**Comment by jrieken** [comment]
_From @bpasero on December 25, 2015 10:17_

This is currently not supported as far as I know.

**Comment by jrieken** [comment]
_From @EmYeuCoGiao on December 25, 2015 10:26_

Thanks you for reply :+1:

**Comment by DustinCampbell** [comment]
This will require a new Roslyn API.

**Comment by dmccaffery** [comment]
There is a third-party extension that (mostly) provides this functionality:

https://marketplace.visualstudio.com/items?itemName=k--kato.docomment

What is required of roslyn to achieve this? The fact that it does not support navigating comments within the document?

**Comment by DustinCampbell** [comment]
I need to expose a new API from Roslyn so that the same feature is not simply re-implemented inside of OmniSharp. Remember, this feature already exists in Roslyn today, and it's a little tricky to get right. The feature is not just generating XML doc comments on ///, but also inserting /// on enter, handling indents properly, getting undo behavior to be correct, not interfering with XML doc comment completion lists, etc.

> What is required of roslyn to achieve this? The fact that it does support navigating comments within the document".

I'm not sure what you mean by this. There's nothing within Roslyn that disallows writing such a thing. Also, it's not clear to me why you would think navigating comments would be related to XML doc comment generation. Could you be a bit more precise?

As I mentioned, the feature already exists in Roslyn. I need to expose that feature as an API so that it can be used in OmniSharp.

**Comment by dmccaffery** [comment]
@DustinCampbell What I meant was, there was an issue sometime ago within Roslyn (probably specifically as it relates to analyzers) whereby navigating the document tree would not expose comment blocks -- it would skip over them. I assumed something similar might be in play here. At any rate, I am no expert when it comes to the roslyn APIs, so I will definitely take your word for it. :)

**Comment by vanillajonathan** [comment]
It would be useful even if it didn't generate the `<param>` tags. Just inserting a blank template with a  `<summary>` tag would be useful.

Also just basic intellisense for the common tags such as `summary`, `para`, `c`, `returns`, `seealso`, `remarks`, `example`, `code` would be use useful.

So even a basic one without Rosylin would be appreciated. :)

**Comment by bernardbr** [comment]
I'm using this extension: https://marketplace.visualstudio.com/items?itemName=k--kato.docomment and it solves the most common scenarios.

**Comment by osterhoutan** [comment]
Even just adding intellisense/code-completion for the xml tags like exists in visual studio would be amazing.
Especially since currently vs-code default code snippets do not work in C# comments.
