### ISSUE TITLE
More complete Unity Support

### ISSUE THREAD

**Issue by jrieken** [OmniSharp/omnisharp-vscode#9]
_From @hadi77ir on December 18, 2015 22:48_

It's just OmniSharp and C# support, not Unity integration. Even with using a Unity Editor Plugin, nothing changes: We have only C# support without UnityEngine.UI, UnityEngine.EventSystems, UnityEngine.\* and UnityEditor namespaces!

Also we don't have any Boo or UnityScript support when we're using VS Code, So we had to switch back to the MonoDevelop.

What Unity Community wants from Visual Studio Code is:
1. Implementing UnityScript and Boo Support
2. Fixing assembly referencing problems (specially for UnityEngine.UI, but I think that it's a Unity problem, not an OmniSharp bug)
3. Intellisense for Boo and UnityScript (by using Roslyn, since they're .NET languages)

_Copied from original issue: Microsoft/vscode#1461_

**Comment by jrieken** [comment]
_From @egamma on December 20, 2015 18:29_

@hadi77ir the feature request makes sense, but this is also a great opportunity for a Code contribution/extension from to the Unity community.

**Comment by jrieken** [comment]
Nothing I am aware of. Maybe @hadi77ir knows?

**Comment by hadi77ir** [comment]
They've officially dropped support for it.
AFAIK all of UnityScript code (compiler, MonoDevelop extensions, etc.) were available at [Unity Technologies](https://github.com/Unity-Technologies) repositories, but now I can't find them. (I think they have deleted the repos instead of archiving).
But the community may revive it some day by writing a new compiler and plugging support into Unity, who knows? :)

@jrieken As of now, UnityScript is of no use. You may close this issue. :wave:

**Comment by akshita31** [comment]
Thanks @hadi77ir. In future, Please let us know if there are any features that help Unity developers that might be interesting to take up for the C# extension.
