### ISSUE TITLE
Add a menu entry to the command palette for 'dotnet new' command.

### ISSUE THREAD

**Issue by hashhar** [OmniSharp/omnisharp-vscode#944]
VS Code version: 1.7.1
C# Extension version: 1.5

## Expected  behavior
A menu entry in the command palette to run `dotnet new` (similar to how we have `dotnet restore`.

**Comment by DustinCampbell** [comment]
I'm interested in thinking through the scenario for this. What directory would 'dotnet new' run in? Is the assumption that the user would create a directory, open that empty directory in VS Code and then use the 'dotnet new' command? If so, I'm not sure I see the value. Especially since the user could just open the Integrated Terminal window in VS Code and run 'dotnet new'. Could you clarify how you think this should work?

**Comment by hashhar** [comment]
I was thinking along similar lines. I think it is fine the way it is right now since the `dotnet new` command is a one off case. I would like to keep this here for a while to see if other people have any ideas for this. You may close this issue otherwise.
