### ISSUE TITLE
Simple dependency resolution

### ISSUE THREAD

**Issue by lgreenlee** [OmniSharp/omnisharp-vscode#963]
As a developer I would like to add a dependency to a buildable project folder located anywhere on my file system. It should be as simple as providing a path to a folder with a project.json or .csproj file located in its root.

At the moment it not possible to do this in this way - it is overly constraining to require that projects be located in the same file structure in order to be built together.

**Comment by DustinCampbell** [comment]
This should be possible with the move to .csproj .NET Core projects. You should be able to specify a project reference to a project outside of the open folder that will be included correctly.

**Comment by DustinCampbell** [comment]
I just tried this and it doesn't work like I'd hoped. I'll need to tweak omnisharp-roslyn to make this work.

**Comment by cruz82** [comment]
For csproj based projects, it was possible to workaround this by restoring and building using the CLI then rerunning omnisharp.

In versions < 1.9.0 you did not have to add the referenced projects in the solution file but in version 1.9.0, you have to add those projects to the solution file to make it work. The CLI (v1.0.1) does not require the referenced projects to be added to the solution.

**Comment by DustinCampbell** [comment]
Thanks for the added detail @cruz82: I understand what happened now. Around December, we introduced a regression into OmniSharp, which caused project references to get added *twice* -- once for the project, and once for its output binary. This resulted in projects getting ambiguity errors (https://github.com/OmniSharp/omnisharp-roslyn/issues/795, PR: https://github.com/OmniSharp/omnisharp-roslyn/pull/815). However, this regression also had a side effect in that it could handle the scenario that you described.

I'm working on just fixing this properly so that both scenarios work.
