### ISSUE TITLE
Add the ability to debug Xunit tests.

### ISSUE THREAD

**Issue by PradeepLoganathan** [OmniSharp/omnisharp-vscode#995]
## Environment data
`dotnet --info` output:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|githistory|donjayamanne|0.1.0|
|javadebugger|donjayamanne|0.0.2|
|rest-client|humao|0.10.4|
|Angular2|johnpapa|1.0.2|
|csharp|ms-vscode|1.5.0-beta8|
|vscode-docker|PeterJausovec|0.0.7|
|java|redhat|0.0.7|

I don't see an option to debug xunit tests. after creating tests in xunit I am able to run it successfully against my target library. I am unable to debug tests since the debug option is expecting a main entry point.

**Comment by DustinCampbell** [comment]
My apologies for letting this grow so stale. Here is the current state of the world:

* This **should** work with project.json-based .NET Core projects.
* There is a bug with detecting xUnit tests defined in nested classes that should be fixed in 1.7. (https://github.com/OmniSharp/omnisharp-vscode/issues/1151)
* This does not work with .csproj-based .NET Core projects yet. This is a fairly large work item to fix and we're planning to do it for the 1.8 release. (https://github.com/OmniSharp/omnisharp-vscode/issues/1100)

I'm going to go ahead and close this issue as the work is being tracked elsewhere.
