### ISSUE TITLE
Debug adapter process has terminated unexpectedly

### ISSUE THREAD

**Issue by weinand** [OmniSharp/omnisharp-vscode#997]
_From @GabrielGGuerreiro on November 28, 2016 2:33_

- VSCode Version: 1.8.0-insider
- OS Version: Ubuntu 16.10
- dotnet --version: 1.0.0-preview2-1-003177

Steps to Reproduce:

1. sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ yakkety main" > /etc/apt/sources.list.d/dotnetdev.list'
2. sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893
3. sudo apt-get update
4. sudo apt-get install dotnet-dev-1.0.0-preview2.1-003177
5. mkdir hwapp
6. cd hwapp
7. dotnet new
8. dotnet restore
9. dotnet run (this runned fine)
10. head to https://code.visualstudio.com/insiders download the .deb which will download the vscode-insiders build
11. open the folder you created in the hwapp example
12. place a breakpoint in the Console.WriteLine("Hello World!");
13. Press F5 or Click the Debug Icon on the left and click on the run icon

![debugger error](https://cloud.githubusercontent.com/assets/13945178/20654636/3d8dc688-b502-11e6-8ebb-e60ca1f22314.png)

_Copied from original issue: Microsoft/vscode#16124_

**Comment by weinand** [comment]
@GabrielGGuerreiro please file .net/C# related issues against this repo https://github.com/OmniSharp/omnisharp-vscode

**Comment by gregg-miskelly** [comment]
@GabrielGGuerreiro the debugger isn't yet supported on Ubuntu 16.10. We are tracking this with https://github.com/OmniSharp/omnisharp-vscode/issues/956. We hope to have a beta out this week.

**Comment by khizerrehands** [comment]
Any one could help ? i have updated typescript 2.1.5 to 2.1.6 in previous version my debugger was working fine in VS Code editor but due to update it is giving me following error! 
![137a4c7c-ff7b-11e6-99b6-fecac54f5802](https://cloud.githubusercontent.com/assets/26121221/23554879/a98e853e-0048-11e7-80af-fce099e25e14.png)

My Launch.json File is
![44a500ee-ff7b-11e6-9b41-2f3c8fe10707](https://cloud.githubusercontent.com/assets/26121221/23554899/b97719ac-0048-11e7-9d3c-4871c736bb50.png)

**Comment by gregg-miskelly** [comment]
@khizerrehands this is the repo for the C# debugger. It looks like you are having a problem with the Chrome debugger. So you will need to find their repo.
